<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Rihanna Razavi">

<title>Lab 1 - Redwood Trees: Temperature-Humidity Relationships Across Diffrent Canopy Heights</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="lab1_python_files/libs/clipboard/clipboard.min.js"></script>
<script src="lab1_python_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="lab1_python_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="lab1_python_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="lab1_python_files/libs/quarto-html/popper.min.js"></script>
<script src="lab1_python_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="lab1_python_files/libs/quarto-html/anchor.min.js"></script>
<link href="lab1_python_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="lab1_python_files/libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="lab1_python_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="lab1_python_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="lab1_python_files/libs/bootstrap/bootstrap-07856ccd07157181b6c57ddbe7d8c2c1.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#data-overview-and-collection" id="toc-data-overview-and-collection" class="nav-link" data-scroll-target="#data-overview-and-collection">Data Overview and Collection</a></li>
  <li><a href="#data-cleaning" id="toc-data-cleaning" class="nav-link" data-scroll-target="#data-cleaning">Data Cleaning</a>
  <ul class="collapse">
  <li><a href="#step-1-load-datasets-and-examine-voltage-distributions" id="toc-step-1-load-datasets-and-examine-voltage-distributions" class="nav-link" data-scroll-target="#step-1-load-datasets-and-examine-voltage-distributions">Step 1: Load Datasets and Examine Voltage Distributions</a></li>
  <li><a href="#step-2-empirical-voltage-calibration" id="toc-step-2-empirical-voltage-calibration" class="nav-link" data-scroll-target="#step-2-empirical-voltage-calibration">Step 2: Empirical Voltage Calibration</a></li>
  <li><a href="#step-3-apply-conversion-and-merge-datasets" id="toc-step-3-apply-conversion-and-merge-datasets" class="nav-link" data-scroll-target="#step-3-apply-conversion-and-merge-datasets">Step 3: Apply Conversion and Merge Datasets</a></li>
  <li><a href="#step-4-clean-the-merged-dataset" id="toc-step-4-clean-the-merged-dataset" class="nav-link" data-scroll-target="#step-4-clean-the-merged-dataset">Step 4: Clean the Merged Dataset</a></li>
  <li><a href="#data-quality-issues-and-cleaning-procedures" id="toc-data-quality-issues-and-cleaning-procedures" class="nav-link" data-scroll-target="#data-quality-issues-and-cleaning-procedures">Data Quality Issues and Cleaning Procedures</a>
  <ul class="collapse">
  <li><a href="#voltage-scale-inconsistency" id="toc-voltage-scale-inconsistency" class="nav-link" data-scroll-target="#voltage-scale-inconsistency">1. Voltage Scale Inconsistency</a></li>
  <li><a href="#invalid-voltage-readings" id="toc-invalid-voltage-readings" class="nav-link" data-scroll-target="#invalid-voltage-readings">2. Invalid Voltage Readings</a></li>
  <li><a href="#impossible-physical-values" id="toc-impossible-physical-values" class="nav-link" data-scroll-target="#impossible-physical-values">3. Impossible Physical Values</a></li>
  <li><a href="#duplicate-measurements" id="toc-duplicate-measurements" class="nav-link" data-scroll-target="#duplicate-measurements">4. Duplicate Measurements</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#exploratory-data-analysis" id="toc-exploratory-data-analysis" class="nav-link" data-scroll-target="#exploratory-data-analysis">Exploratory Data Analysis</a>
  <ul class="collapse">
  <li><a href="#finding-1-temperature-humidity-relationships-differ-by-canopy-layer" id="toc-finding-1-temperature-humidity-relationships-differ-by-canopy-layer" class="nav-link" data-scroll-target="#finding-1-temperature-humidity-relationships-differ-by-canopy-layer">Finding 1: Temperature-Humidity Relationships Differ by Canopy Layer</a></li>
  <li><a href="#finding-2-temperature-distributions-are-similar-across-canopy-layers" id="toc-finding-2-temperature-distributions-are-similar-across-canopy-layers" class="nav-link" data-scroll-target="#finding-2-temperature-distributions-are-similar-across-canopy-layers">Finding 2: Temperature Distributions Are Similar Across Canopy Layers</a></li>
  <li><a href="#finding-3-height-influences-temperature-humidity-coupling-strength" id="toc-finding-3-height-influences-temperature-humidity-coupling-strength" class="nav-link" data-scroll-target="#finding-3-height-influences-temperature-humidity-coupling-strength">Finding 3: Height Influences Temperature-Humidity Coupling Strength</a></li>
  <li><a href="#finding-4-humidity-relationship-with-height" id="toc-finding-4-humidity-relationship-with-height" class="nav-link" data-scroll-target="#finding-4-humidity-relationship-with-height">Finding 4: Humidity Relationship with Height</a></li>
  <li><a href="#finding-5-humidity-distributions-by-canopy-layer" id="toc-finding-5-humidity-distributions-by-canopy-layer" class="nav-link" data-scroll-target="#finding-5-humidity-distributions-by-canopy-layer">Finding 5: Humidity Distributions by Canopy Layer</a></li>
  </ul></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">Discussion</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Lab 1 - Redwood Trees: Temperature-Humidity Relationships Across Diffrent Canopy Heights</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Rihanna Razavi </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<div id="setup" class="cell" data-execution_count="1">
<details class="code-fold">
<summary>Show Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> sys</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>sys.path.append(<span class="st">".."</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> os.path <span class="im">import</span> join <span class="im">as</span> oj</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> python.load <span class="im">import</span> load_dates_data, load_mote_location_data, load_redwood_data</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> python.clean <span class="im">import</span> clean_dates_data, clean_mote_location_data, clean_redwood_data</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> python.prepare <span class="im">import</span> prepare_analysis_data</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> python.stats <span class="im">import</span> calculate_data_quality_metrics</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>DATA_PATH <span class="op">=</span> oj(<span class="st">".."</span>, <span class="st">"data"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>Understanding how environmental conditions vary in forest canopies is essential for predicting tree physiology, carbon cycling, and ecosystem responses to climate change. Temperature and humidity are fundamental drivers of photosynthesis and transpiration in trees, yet their interactions within tall forest canopies remain poorly understood due to the difficulty of measuring these variables at multiple heights all together.</p>
<p>Coastal redwood (<em>Sequoia sempervirens</em>) trees create complex microclimates due to their extreme height (often exceeding 70 meters) and dense canopy structure. Traditional ecological theory suggests that upper canopy positions should be hotter and drier due to direct solar exposure, while lower canopy positions should be cooler and more humid. However, the actual temperature-humidity relationships at different canopy heights, and how these relationships reflect different environmental processes, have rarely been quantified at fine spatial scales.</p>
<p><strong>Research Question:</strong> How does the relationship between temperature and humidity vary across different vertical positions within a coastal redwood canopy?</p>
<p>This analysis uses high-resolution sensor network data from Tolle et al.&nbsp;(2005) collected over 44 days in a single redwood tree to examine how temperature-humidity relationships differ between lower, middle, and upper canopy positions.</p>
</section>
<section id="data-overview-and-collection" class="level1">
<h1>Data Overview and Collection</h1>
<div id="load-data" class="cell" data-execution_count="2">
<details class="code-fold">
<summary>Show Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load individual datasets</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>dates_orig <span class="op">=</span> load_dates_data(DATA_PATH)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>motes_orig <span class="op">=</span> load_mote_location_data(DATA_PATH)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>redwood_net_orig <span class="op">=</span> load_redwood_data(DATA_PATH, source<span class="op">=</span><span class="st">"net"</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>redwood_log_orig <span class="op">=</span> load_redwood_data(DATA_PATH, source<span class="op">=</span><span class="st">"log"</span>)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"=== ORIGINAL DATASETS ==="</span>)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Network dataset: </span><span class="sc">{</span><span class="bu">len</span>(redwood_net_orig)<span class="sc">:,}</span><span class="ss"> observations"</span>)</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Log dataset: </span><span class="sc">{</span><span class="bu">len</span>(redwood_log_orig)<span class="sc">:,}</span><span class="ss"> observations"</span>)</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Number of unique sensors (net): </span><span class="sc">{</span>redwood_net_orig[<span class="st">'nodeid'</span>]<span class="sc">.</span>nunique()<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Number of unique sensors (log): </span><span class="sc">{</span>redwood_log_orig[<span class="st">'nodeid'</span>]<span class="sc">.</span>nunique()<span class="sc">}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>=== ORIGINAL DATASETS ===
Network dataset: 114,980 observations
Log dataset: 301,056 observations
Number of unique sensors (net): 31
Number of unique sensors (log): 72</code></pre>
</div>
</div>
</section>
<section id="data-cleaning" class="level1">
<h1>Data Cleaning</h1>
<section id="step-1-load-datasets-and-examine-voltage-distributions" class="level2">
<h2 class="anchored" data-anchor-id="step-1-load-datasets-and-examine-voltage-distributions">Step 1: Load Datasets and Examine Voltage Distributions</h2>
<div id="load-datasets" class="cell" data-execution_count="3">
<details class="code-fold">
<summary>Show Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load net and log datasets separately</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>redwood_net_orig <span class="op">=</span> load_redwood_data(DATA_PATH, source<span class="op">=</span><span class="st">"net"</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>redwood_log_orig <span class="op">=</span> load_redwood_data(DATA_PATH, source<span class="op">=</span><span class="st">"log"</span>)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"=== ORIGINAL DATASETS ==="</span>)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Network dataset: </span><span class="sc">{</span><span class="bu">len</span>(redwood_net_orig)<span class="sc">:,}</span><span class="ss"> observations"</span>)</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Log dataset: </span><span class="sc">{</span><span class="bu">len</span>(redwood_log_orig)<span class="sc">:,}</span><span class="ss"> observations"</span>)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>net_voltage_mean <span class="op">=</span> redwood_net_orig[<span class="st">'voltage'</span>].mean()</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>log_voltage_mean <span class="op">=</span> redwood_log_orig[<span class="st">'voltage'</span>].mean()</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>net_voltage_max <span class="op">=</span> redwood_net_orig[<span class="st">'voltage'</span>].<span class="bu">max</span>()</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>log_voltage_max <span class="op">=</span> redwood_log_orig[<span class="st">'voltage'</span>].<span class="bu">max</span>()</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">Net voltage: mean=</span><span class="sc">{</span>net_voltage_mean<span class="sc">:.2f}</span><span class="ss">, max=</span><span class="sc">{</span>net_voltage_max<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Log voltage: mean=</span><span class="sc">{</span>log_voltage_mean<span class="sc">:.2f}</span><span class="ss">, max=</span><span class="sc">{</span>log_voltage_max<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> net_voltage_max <span class="op">&gt;</span> <span class="dv">100</span> <span class="kw">and</span> log_voltage_max <span class="op">&lt;</span> <span class="dv">10</span>:</span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"Net dataset: Raw ADC values (0-1023)"</span>)</span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"Log dataset: Actual voltages (0-3.3V)"</span>)</span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"These need to be aligned before merging!"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>=== ORIGINAL DATASETS ===
Network dataset: 114,980 observations
Log dataset: 301,056 observations

Net voltage: mean=292.79, max=1023.00
Log voltage: mean=2.51, max=3.03
Net dataset: Raw ADC values (0-1023)
Log dataset: Actual voltages (0-3.3V)
These need to be aligned before merging!</code></pre>
</div>
</div>
</section>
<section id="step-2-empirical-voltage-calibration" class="level2">
<h2 class="anchored" data-anchor-id="step-2-empirical-voltage-calibration">Step 2: Empirical Voltage Calibration</h2>
<div id="dd5d27c8" class="cell" data-execution_count="4">
<details class="code-fold">
<summary>Show Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> python.clean <span class="im">import</span> find_empirical_voltage_conversion</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Finding empirical conversion by matching distributions</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="co">#it's a heuristic common approach</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>conversion_factor, conversion_offset, calibration_fig <span class="op">=</span> find_empirical_voltage_conversion(</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>    redwood_net_orig,</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>    redwood_log_orig</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss"> EMPIRICAL CONVERSION FORMULA:"</span>)</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"   V_corrected = </span><span class="sc">{</span>conversion_factor<span class="sc">:.6f}</span><span class="ss"> × V_net + </span><span class="sc">{</span>conversion_offset<span class="sc">:.6f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
=== EMPIRICAL VOLTAGE ALIGNMENT ===
Net: n=114,980, mean=292.79, range=[198.00, 1023.00]
Log: n=301,056, mean=2.51, range=[0.01, 3.03]

=== METHOD 1: Percentile Matching ===
Net percentiles: 25%=218.0, 50%=223.0, 75%=227.0
Log percentiles: 25%=2.63, 50%=2.70, 75%=2.78

Linear fit: log_V = 0.016291 * net_V + -0.926464

=== METHOD 2: Range Matching ===
Range matching: log_V = 0.003662 * net_V + -0.716010

=== AFTER CONVERSION ===
Net converted: mean=3.84, range=[2.30, 15.74]
Log original:  mean=2.51, range=[0.01, 3.03]
Mean difference: 1.337V

 EMPIRICAL CONVERSION FORMULA:
   V_corrected = 0.016291 × V_net + -0.926464</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="lab1_python_files/figure-html/cell-5-output-2.png" width="1719" height="950" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="cell-calibration-plot" class="cell" data-execution_count="5">
<details class="code-fold">
<summary>Show Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>plt.figure(calibration_fig.number)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div id="calibration-plot" class="cell-output cell-output-display">
<pre><code>&lt;Figure size 672x480 with 0 Axes&gt;</code></pre>
<p>Empirical voltage calibration by matching distribution percentiles across log and net (My own idea). Top row: original distributions and percentile-based linear fit showing how to align them. Bottom row: distributions after conversion with overlay (left), valid range zoom (middle), and Q-Q plot confirming alignment (right).</p>
</div>
</div>
<p>Rather than relying on theoretical conversion formulas that may not reflect the actual hardware configuration, we use an empirical approach to align the voltage distributions. We match the 25th, 50th, and 75th percentiles between the Net and Log datasets to find a linear transformation (scale + offset) that makes the distributions align. This data-driven method accounts for any calibration differences, reference voltage variations, or systematic offsets between the two data collection systems.</p>
</section>
<section id="step-3-apply-conversion-and-merge-datasets" class="level2">
<h2 class="anchored" data-anchor-id="step-3-apply-conversion-and-merge-datasets">Step 3: Apply Conversion and Merge Datasets</h2>
<div id="apply-conversion-merge" class="cell" data-execution_count="6">
<details class="code-fold">
<summary>Show Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Apply empirical conversion to net dataset</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>redwood_net_converted <span class="op">=</span> redwood_net_orig.copy()</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>redwood_net_converted[<span class="st">'voltage'</span>] <span class="op">=</span> (redwood_net_orig[<span class="st">'voltage'</span>] <span class="op">*</span> conversion_factor <span class="op">+</span> conversion_offset)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"=== VOLTAGE AFTER EMPIRICAL CONVERSION ==="</span>)</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Net converted: mean=</span><span class="sc">{</span>redwood_net_converted[<span class="st">'voltage'</span>]<span class="sc">.</span>mean()<span class="sc">:.2f}</span><span class="ss">V, range=[</span><span class="sc">{</span>redwood_net_converted[<span class="st">'voltage'</span>]<span class="sc">.</span><span class="bu">min</span>()<span class="sc">:.2f}</span><span class="ss">, </span><span class="sc">{</span>redwood_net_converted[<span class="st">'voltage'</span>]<span class="sc">.</span><span class="bu">max</span>()<span class="sc">:.2f}</span><span class="ss">]"</span>)</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Log original:  mean=</span><span class="sc">{</span>redwood_log_orig[<span class="st">'voltage'</span>]<span class="sc">.</span>mean()<span class="sc">:.2f}</span><span class="ss">V, range=[</span><span class="sc">{</span>redwood_log_orig[<span class="st">'voltage'</span>]<span class="sc">.</span><span class="bu">min</span>()<span class="sc">:.2f}</span><span class="ss">, </span><span class="sc">{</span>redwood_log_orig[<span class="st">'voltage'</span>]<span class="sc">.</span><span class="bu">max</span>()<span class="sc">:.2f}</span><span class="ss">]"</span>)</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Mean difference after conversion: </span><span class="sc">{</span><span class="bu">abs</span>(redwood_net_converted[<span class="st">'voltage'</span>].mean() <span class="op">-</span> redwood_log_orig[<span class="st">'voltage'</span>].mean())<span class="sc">:.3f}</span><span class="ss">V"</span>)</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>redwood_net_converted[<span class="st">'source'</span>] <span class="op">=</span> <span class="st">'net'</span></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>redwood_log_orig[<span class="st">'source'</span>] <span class="op">=</span> <span class="st">'log'</span></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>redwood_merged <span class="op">=</span> pd.concat([redwood_net_converted, redwood_log_orig], ignore_index<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Before removing duplicates: </span><span class="sc">{</span><span class="bu">len</span>(redwood_merged)<span class="sc">:,}</span><span class="ss">"</span>)</span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove duplicates (same sensor, same time, same measurement period)</span></span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a>redwood_merged <span class="op">=</span> redwood_merged.drop_duplicates(</span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a>    subset<span class="op">=</span>[<span class="st">'nodeid'</span>, <span class="st">'result_time'</span>, <span class="st">'epoch'</span>],</span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a>    keep<span class="op">=</span><span class="st">'first'</span></span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-22"><a href="#cb10-22" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"After removing duplicates: </span><span class="sc">{</span><span class="bu">len</span>(redwood_merged)<span class="sc">:,}</span><span class="ss">"</span>)</span>
<span id="cb10-23"><a href="#cb10-23" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">Merged voltage statistics:"</span>)</span>
<span id="cb10-24"><a href="#cb10-24" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  Mean: </span><span class="sc">{</span>redwood_merged[<span class="st">'voltage'</span>]<span class="sc">.</span>mean()<span class="sc">:.2f}</span><span class="ss">V"</span>)</span>
<span id="cb10-25"><a href="#cb10-25" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  Min: </span><span class="sc">{</span>redwood_merged[<span class="st">'voltage'</span>]<span class="sc">.</span><span class="bu">min</span>()<span class="sc">:.2f}</span><span class="ss">V"</span>)</span>
<span id="cb10-26"><a href="#cb10-26" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  Max: </span><span class="sc">{</span>redwood_merged[<span class="st">'voltage'</span>]<span class="sc">.</span><span class="bu">max</span>()<span class="sc">:.2f}</span><span class="ss">V"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>=== VOLTAGE AFTER EMPIRICAL CONVERSION ===
Net converted: mean=3.84V, range=[2.30, 15.74]
Log original:  mean=2.51V, range=[0.01, 3.03]
Mean difference after conversion: 1.337V
Before removing duplicates: 416,036
After removing duplicates: 407,750

Merged voltage statistics:
  Mean: 2.88V
  Min: 0.01V
  Max: 15.74V</code></pre>
</div>
</div>
</section>
<section id="step-4-clean-the-merged-dataset" class="level2">
<h2 class="anchored" data-anchor-id="step-4-clean-the-merged-dataset">Step 4: Clean the Merged Dataset</h2>
<div id="abbda85e" class="cell" data-execution_count="7">
<details class="code-fold">
<summary>Show Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> python.clean <span class="im">import</span> clean_redwood_data, clean_dates_data, clean_mote_location_data</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>dates_df <span class="op">=</span> clean_dates_data(dates_orig)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>motes_df <span class="op">=</span> clean_mote_location_data(motes_orig)</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>redwood_all_df <span class="op">=</span> clean_redwood_data(redwood_merged)</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate metrics</span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>quality_metrics <span class="op">=</span> calculate_data_quality_metrics(redwood_merged, redwood_all_df)</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"=== DATA CLEANING SUMMARY ==="</span>)</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Original (merged): </span><span class="sc">{</span>quality_metrics[<span class="st">'original_rows'</span>]<span class="sc">:,}</span><span class="ss">"</span>)</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Cleaned: </span><span class="sc">{</span>quality_metrics[<span class="st">'cleaned_rows'</span>]<span class="sc">:,}</span><span class="ss">"</span>)</span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Removed: </span><span class="sc">{</span>quality_metrics[<span class="st">'removed_rows'</span>]<span class="sc">:,}</span><span class="ss"> (</span><span class="sc">{</span><span class="dv">100</span> <span class="op">-</span> quality_metrics[<span class="st">'retention_pct'</span>]<span class="sc">:.1f}</span><span class="ss">%)"</span>)</span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Retention: </span><span class="sc">{</span>quality_metrics[<span class="st">'retention_pct'</span>]<span class="sc">:.1f}</span><span class="ss">%"</span>)</span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">Cleaned voltage statistics:"</span>)</span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  Mean: </span><span class="sc">{</span>redwood_all_df[<span class="st">'voltage'</span>]<span class="sc">.</span>mean()<span class="sc">:.2f}</span><span class="ss">V"</span>)</span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  Min: </span><span class="sc">{</span>redwood_all_df[<span class="st">'voltage'</span>]<span class="sc">.</span><span class="bu">min</span>()<span class="sc">:.2f}</span><span class="ss">V"</span>)</span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  Max: </span><span class="sc">{</span>redwood_all_df[<span class="st">'voltage'</span>]<span class="sc">.</span><span class="bu">max</span>()<span class="sc">:.2f}</span><span class="ss">V"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>=== DATA CLEANING SUMMARY ===
Original (merged): 407,750
Cleaned: 363,629
Removed: 44,121 (10.8%)
Retention: 89.2%

Cleaned voltage statistics:
  Mean: 2.55V
  Min: 0.58V
  Max: 3.50V</code></pre>
</div>
</div>
<div id="cell-voltage-before-after" class="cell" data-execution_count="8">
<details class="code-fold">
<summary>Show Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>fig, (ax1, ax2) <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">14</span>, <span class="dv">5</span>))</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Before cleaning</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>ax1.hist(redwood_merged[<span class="st">'voltage'</span>].dropna(), bins<span class="op">=</span><span class="dv">50</span>, alpha<span class="op">=</span><span class="fl">0.7</span>,</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>        color<span class="op">=</span><span class="st">'orange'</span>, edgecolor<span class="op">=</span><span class="st">'darkorange'</span>)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>ax1.axvline(<span class="dv">0</span>, color<span class="op">=</span><span class="st">'red'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>, linewidth<span class="op">=</span><span class="dv">2</span>, label<span class="op">=</span><span class="st">'Valid range'</span>)</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>ax1.axvline(<span class="dv">4</span>, color<span class="op">=</span><span class="st">'red'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>, linewidth<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>ax1.axvline(<span class="fl">2.4</span>, color<span class="op">=</span><span class="st">'green'</span>, linestyle<span class="op">=</span><span class="st">':'</span>, linewidth<span class="op">=</span><span class="fl">1.5</span>, alpha<span class="op">=</span><span class="fl">0.7</span>, label<span class="op">=</span><span class="st">'Typical range'</span>)</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>ax1.axvline(<span class="fl">3.0</span>, color<span class="op">=</span><span class="st">'green'</span>, linestyle<span class="op">=</span><span class="st">':'</span>, linewidth<span class="op">=</span><span class="fl">1.5</span>, alpha<span class="op">=</span><span class="fl">0.7</span>)</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>ax1.set_xlabel(<span class="st">'Voltage (V)'</span>, fontsize<span class="op">=</span><span class="dv">12</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>ax1.set_ylabel(<span class="st">'Frequency'</span>, fontsize<span class="op">=</span><span class="dv">12</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>ax1.set_title(<span class="ss">f'Before Cleaning</span><span class="ch">\n</span><span class="ss">n = </span><span class="sc">{</span><span class="bu">len</span>(redwood_merged)<span class="sc">:,}</span><span class="ss">'</span>, fontsize<span class="op">=</span><span class="dv">14</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>ax1.legend()</span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>ax1.grid(<span class="va">True</span>, alpha<span class="op">=</span><span class="fl">0.3</span>)</span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a><span class="co"># After cleaning</span></span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a>ax2.hist(redwood_all_df[<span class="st">'voltage'</span>].dropna(), bins<span class="op">=</span><span class="dv">50</span>, alpha<span class="op">=</span><span class="fl">0.7</span>,</span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a>        color<span class="op">=</span><span class="st">'green'</span>, edgecolor<span class="op">=</span><span class="st">'darkgreen'</span>)</span>
<span id="cb14-19"><a href="#cb14-19" aria-hidden="true" tabindex="-1"></a>ax2.axvline(<span class="dv">0</span>, color<span class="op">=</span><span class="st">'red'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>, linewidth<span class="op">=</span><span class="dv">2</span>, label<span class="op">=</span><span class="st">'Valid range'</span>)</span>
<span id="cb14-20"><a href="#cb14-20" aria-hidden="true" tabindex="-1"></a>ax2.axvline(<span class="dv">4</span>, color<span class="op">=</span><span class="st">'red'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>, linewidth<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb14-21"><a href="#cb14-21" aria-hidden="true" tabindex="-1"></a>ax2.axvline(<span class="fl">2.4</span>, color<span class="op">=</span><span class="st">'blue'</span>, linestyle<span class="op">=</span><span class="st">':'</span>, linewidth<span class="op">=</span><span class="fl">1.5</span>, alpha<span class="op">=</span><span class="fl">0.7</span>, label<span class="op">=</span><span class="st">'Typical range'</span>)</span>
<span id="cb14-22"><a href="#cb14-22" aria-hidden="true" tabindex="-1"></a>ax2.axvline(<span class="fl">3.0</span>, color<span class="op">=</span><span class="st">'blue'</span>, linestyle<span class="op">=</span><span class="st">':'</span>, linewidth<span class="op">=</span><span class="fl">1.5</span>, alpha<span class="op">=</span><span class="fl">0.7</span>)</span>
<span id="cb14-23"><a href="#cb14-23" aria-hidden="true" tabindex="-1"></a>ax2.set_xlabel(<span class="st">'Voltage (V)'</span>, fontsize<span class="op">=</span><span class="dv">12</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb14-24"><a href="#cb14-24" aria-hidden="true" tabindex="-1"></a>ax2.set_ylabel(<span class="st">'Frequency'</span>, fontsize<span class="op">=</span><span class="dv">12</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb14-25"><a href="#cb14-25" aria-hidden="true" tabindex="-1"></a>ax2.set_title(<span class="ss">f'After Cleaning</span><span class="ch">\n</span><span class="ss">n = </span><span class="sc">{</span><span class="bu">len</span>(redwood_all_df)<span class="sc">:,}</span><span class="ss">'</span>, fontsize<span class="op">=</span><span class="dv">14</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb14-26"><a href="#cb14-26" aria-hidden="true" tabindex="-1"></a>ax2.legend()</span>
<span id="cb14-27"><a href="#cb14-27" aria-hidden="true" tabindex="-1"></a>ax2.grid(<span class="va">True</span>, alpha<span class="op">=</span><span class="fl">0.3</span>)</span>
<span id="cb14-28"><a href="#cb14-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-29"><a href="#cb14-29" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb14-30"><a href="#cb14-30" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div id="voltage-before-after" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="lab1_python_files/figure-html/voltage-before-after-output-1.png" width="1335" height="468" class="figure-img"></p>
<figcaption>Voltage distribution before and after cleaning. Left: merged data after empirical conversion but before quality filtering shows the full range. Right: after removing invalid readings (outside 0-4V range) and other quality filters, retaining only reliable measurements.</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="data-quality-issues-and-cleaning-procedures" class="level2">
<h2 class="anchored" data-anchor-id="data-quality-issues-and-cleaning-procedures">Data Quality Issues and Cleaning Procedures</h2>
<p>Through systematic examination, we identified several critical data quality issues:</p>
<section id="voltage-scale-inconsistency" class="level3">
<h3 class="anchored" data-anchor-id="voltage-scale-inconsistency">1. Voltage Scale Inconsistency</h3>
<p>The network and log datasets recorded voltage in fundamentally different scales. The network dataset used raw ADC (analog-to-digital converter) values ranging from 0-1023, while the log dataset stored actual voltages in the 0-3.3V range. Simply merging these datasets would create artificial patterns and invalidate any voltage-based quality filtering.</p>
<p>Rather than applying a theoretical conversion formula (which assumes knowledge of the exact reference voltage and ADC configuration),I used an empirical calibration approach. We matched the statistical distributions of the two datasets by finding the linear transformation (scale factor and offset) that aligns their percentiles. V_corrected = 0.016291 × V_net + -0.926464</p>
</section>
<section id="invalid-voltage-readings" class="level3">
<h3 class="anchored" data-anchor-id="invalid-voltage-readings">2. Invalid Voltage Readings</h3>
<p>We filtered data to retain only readings with voltage between 0-4V. While the typical operating range for these sensors is 2.4-3.0V (shown as dotted green/blue lines in the plots). Values outside 0-4V represent sensor malfunctions or data corruption.</p>
</section>
<section id="impossible-physical-values" class="level3">
<h3 class="anchored" data-anchor-id="impossible-physical-values">3. Impossible Physical Values</h3>
<p>We removed readings that violated physical constraints: - Humidity outside 0-100% (relative humidity cannot exceed saturation or be negative) - Temperature outside -20°C to 50°C (far outside the range possible in coastal California) - Negative PAR values (light intensity cannot be negative)</p>
</section>
<section id="duplicate-measurements" class="level3">
<h3 class="anchored" data-anchor-id="duplicate-measurements">4. Duplicate Measurements</h3>
<p>After merging the network and log datasets, some measurements appeared twice. We removed duplicates by identifying measurements with matching sensor ID, timestamp, and measurement period, keeping only the first occurrence.</p>
</section>
</section>
</section>
<section id="exploratory-data-analysis" class="level1">
<h1>Exploratory Data Analysis</h1>
<div id="prepare-analysis" class="cell" data-execution_count="9">
<details class="code-fold">
<summary>Show Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Prepare analysis-ready dataset with canopy layers</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>analysis_data <span class="op">=</span> prepare_analysis_data(redwood_all_df, motes_df)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Display layer statistics</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"=== OBSERVATIONS BY CANOPY LAYER ==="</span>)</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>layer_counts <span class="op">=</span> analysis_data.groupby(<span class="st">'canopy_layer'</span>).size()</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> layer <span class="kw">in</span> [<span class="st">'Lower'</span>, <span class="st">'Middle'</span>, <span class="st">'Upper'</span>]:</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>layer<span class="sc">}</span><span class="ss"> canopy: </span><span class="sc">{</span>layer_counts[layer]<span class="sc">:,}</span><span class="ss"> observations"</span>)</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Temperature-humidity statistics by layer</span></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">=== TEMPERATURE-HUMIDITY STATISTICS BY LAYER ==="</span>)</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>layer_stats <span class="op">=</span> analysis_data.groupby(<span class="st">'canopy_layer'</span>).agg({</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">'humid_temp'</span>: [<span class="st">'mean'</span>, <span class="st">'std'</span>],</span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>    <span class="st">'humidity'</span>: [<span class="st">'mean'</span>, <span class="st">'std'</span>]</span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>}).<span class="bu">round</span>(<span class="dv">2</span>)</span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(layer_stats)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>=== OBSERVATIONS BY CANOPY LAYER ===
Lower canopy: 59,807 observations
Middle canopy: 183,372 observations
Upper canopy: 114,512 observations

=== TEMPERATURE-HUMIDITY STATISTICS BY LAYER ===
             humid_temp       humidity       
                   mean   std     mean    std
canopy_layer                                 
Lower             15.08  4.96    61.42  22.88
Middle            15.23  4.83    61.38  22.46
Upper             14.73  4.58    64.25  21.79</code></pre>
</div>
</div>
<section id="finding-1-temperature-humidity-relationships-differ-by-canopy-layer" class="level2">
<h2 class="anchored" data-anchor-id="finding-1-temperature-humidity-relationships-differ-by-canopy-layer">Finding 1: Temperature-Humidity Relationships Differ by Canopy Layer</h2>
<div id="cell-finding1-hexbin" class="cell" data-execution_count="10">
<details class="code-fold">
<summary>Show Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> plot_temp_humidity_by_layer(data, figsize<span class="op">=</span>(<span class="dv">16</span>, <span class="dv">5</span>)):</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="co">    Plot temperature vs humidity relationship for different canopy layers</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>    fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">3</span>, figsize<span class="op">=</span>figsize)</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>    colors <span class="op">=</span> {<span class="st">'Lower'</span>: <span class="st">'forestgreen'</span>, <span class="st">'Middle'</span>: <span class="st">'orange'</span>, <span class="st">'Upper'</span>: <span class="st">'crimson'</span>}</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> i, layer <span class="kw">in</span> <span class="bu">enumerate</span>([<span class="st">'Lower'</span>, <span class="st">'Middle'</span>, <span class="st">'Upper'</span>]):</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>        subset <span class="op">=</span> data[data[<span class="st">'canopy_layer'</span>] <span class="op">==</span> layer]</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>        axes[i].hexbin(subset[<span class="st">'humid_temp'</span>], subset[<span class="st">'humidity'</span>], </span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>                       gridsize<span class="op">=</span><span class="dv">30</span>, cmap<span class="op">=</span><span class="st">'YlOrRd'</span>, mincnt<span class="op">=</span><span class="dv">1</span>, alpha<span class="op">=</span><span class="fl">0.8</span>)</span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>        axes[i].set_xlabel(<span class="st">'Temperature (°C)'</span>, fontsize<span class="op">=</span><span class="dv">12</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a>        axes[i].set_ylabel(<span class="st">'Relative Humidity (%)'</span>, fontsize<span class="op">=</span><span class="dv">12</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a>        axes[i].set_title(<span class="ss">f'</span><span class="sc">{</span>layer<span class="sc">}</span><span class="ss"> Canopy'</span>, fontsize<span class="op">=</span><span class="dv">14</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>, </span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a>                         color<span class="op">=</span>colors[layer])</span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a>        axes[i].grid(<span class="va">True</span>, alpha<span class="op">=</span><span class="fl">0.3</span>)</span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a>        n <span class="op">=</span> <span class="bu">len</span>(subset)</span>
<span id="cb17-20"><a href="#cb17-20" aria-hidden="true" tabindex="-1"></a>        axes[i].text(<span class="fl">0.05</span>, <span class="fl">0.95</span>, <span class="ss">f'n = </span><span class="sc">{</span>n<span class="sc">:,}</span><span class="ss">'</span>, transform<span class="op">=</span>axes[i].transAxes,</span>
<span id="cb17-21"><a href="#cb17-21" aria-hidden="true" tabindex="-1"></a>                    fontsize<span class="op">=</span><span class="dv">10</span>, verticalalignment<span class="op">=</span><span class="st">'top'</span>,</span>
<span id="cb17-22"><a href="#cb17-22" aria-hidden="true" tabindex="-1"></a>                    bbox<span class="op">=</span><span class="bu">dict</span>(boxstyle<span class="op">=</span><span class="st">'round'</span>, facecolor<span class="op">=</span><span class="st">'wheat'</span>, alpha<span class="op">=</span><span class="fl">0.5</span>))</span>
<span id="cb17-23"><a href="#cb17-23" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb17-24"><a href="#cb17-24" aria-hidden="true" tabindex="-1"></a>    plt.tight_layout()</span>
<span id="cb17-25"><a href="#cb17-25" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> fig</span>
<span id="cb17-26"><a href="#cb17-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-27"><a href="#cb17-27" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> plot_temp_humidity_by_layer(analysis_data)</span>
<span id="cb17-28"><a href="#cb17-28" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div id="finding1-hexbin" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="lab1_python_files/figure-html/finding1-hexbin-output-1.png" width="1527" height="469" class="figure-img"></p>
<figcaption>Temperature-humidity relationships across three canopy layers. Each panel shows hexbin density plots where darker red colors indicate higher density of observations. The upper canopy shows a clear inverse relationship between temperature and humidity, while the lower canopy shows a more diffuse pattern with points scattered throughout the parameter space.</figcaption>
</figure>
</div>
</div>
</div>
<p>Across all layers, there is a clear negative relationship: as temperature increases, relative humidity decreases. The densest regions (darkest hexes) occur at high humidity and lower temperatures, especially in the Lower Canopy, indicating more frequent cool, moist conditions near the ground. Upper canopy measurements are generally warmer and slightly drier, highlighting consistent vertical microclimatic gradients in temperature and humidity through the forest canopy.</p>
</section>
<section id="finding-2-temperature-distributions-are-similar-across-canopy-layers" class="level2">
<h2 class="anchored" data-anchor-id="finding-2-temperature-distributions-are-similar-across-canopy-layers">Finding 2: Temperature Distributions Are Similar Across Canopy Layers</h2>
<div id="cell-finding2-boxplots" class="cell" data-execution_count="11">
<details class="code-fold">
<summary>Show Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> plot_temperature_by_layer(data, figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">6</span>)):</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">""" Box plot showing temperature distribution across canopy layers</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>    fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>figsize)</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>    layers <span class="op">=</span> [<span class="st">'Lower'</span>, <span class="st">'Middle'</span>, <span class="st">'Upper'</span>]</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>    data_to_plot <span class="op">=</span> [data[data[<span class="st">'canopy_layer'</span>] <span class="op">==</span> layer][<span class="st">'humid_temp'</span>].dropna() </span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>                    <span class="cf">for</span> layer <span class="kw">in</span> layers]</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>    bp <span class="op">=</span> ax.boxplot(data_to_plot, labels<span class="op">=</span>layers, patch_artist<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>                    boxprops<span class="op">=</span><span class="bu">dict</span>(facecolor<span class="op">=</span><span class="st">'lightcoral'</span>, alpha<span class="op">=</span><span class="fl">0.7</span>),</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>                    medianprops<span class="op">=</span><span class="bu">dict</span>(color<span class="op">=</span><span class="st">'darkred'</span>, linewidth<span class="op">=</span><span class="dv">2</span>),</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>                    showmeans<span class="op">=</span><span class="va">True</span>, </span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>                    meanprops<span class="op">=</span><span class="bu">dict</span>(marker<span class="op">=</span><span class="st">'D'</span>, markerfacecolor<span class="op">=</span><span class="st">'blue'</span>, </span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>                                  markeredgecolor<span class="op">=</span><span class="st">'blue'</span>, markersize<span class="op">=</span><span class="dv">8</span>))</span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a>    ax.set_xlabel(<span class="st">'Canopy Layer'</span>, fontsize<span class="op">=</span><span class="dv">13</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a>    ax.set_ylabel(<span class="st">'Temperature (°C)'</span>, fontsize<span class="op">=</span><span class="dv">13</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a>    ax.set_title(<span class="st">'Temperature Distribution by Canopy Layer'</span>, </span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a>                 fontsize<span class="op">=</span><span class="dv">15</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb18-20"><a href="#cb18-20" aria-hidden="true" tabindex="-1"></a>    ax.grid(<span class="va">True</span>, alpha<span class="op">=</span><span class="fl">0.3</span>, axis<span class="op">=</span><span class="st">'y'</span>)</span>
<span id="cb18-21"><a href="#cb18-21" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> i, layer <span class="kw">in</span> <span class="bu">enumerate</span>(layers):</span>
<span id="cb18-22"><a href="#cb18-22" aria-hidden="true" tabindex="-1"></a>        n <span class="op">=</span> <span class="bu">len</span>(data_to_plot[i])</span>
<span id="cb18-23"><a href="#cb18-23" aria-hidden="true" tabindex="-1"></a>        ax.text(i<span class="op">+</span><span class="dv">1</span>, ax.get_ylim()[<span class="dv">0</span>] <span class="op">+</span> <span class="fl">0.5</span>, <span class="ss">f'n=</span><span class="sc">{</span>n<span class="sc">:,}</span><span class="ss">'</span>, </span>
<span id="cb18-24"><a href="#cb18-24" aria-hidden="true" tabindex="-1"></a>               ha<span class="op">=</span><span class="st">'center'</span>, va<span class="op">=</span><span class="st">'bottom'</span>, fontsize<span class="op">=</span><span class="dv">9</span>)</span>
<span id="cb18-25"><a href="#cb18-25" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb18-26"><a href="#cb18-26" aria-hidden="true" tabindex="-1"></a>    plt.tight_layout()</span>
<span id="cb18-27"><a href="#cb18-27" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> fig</span>
<span id="cb18-28"><a href="#cb18-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-29"><a href="#cb18-29" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> plot_temperature_by_layer(analysis_data)</span>
<span id="cb18-30"><a href="#cb18-30" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="lab1_python_files/figure-html/finding2-boxplots-output-1.png" id="finding2-boxplots" width="757" height="565" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The box plots reveal a surprising result: despite being separated by up to 55 meters vertically and experiencing vastly different light environments, all three canopy layers show similar temperature distributions. The median temperatures (red lines) are approximately 15°C for all three layers, and the interquartile ranges (boxes) overlap substantially.</p>
</section>
<section id="finding-3-height-influences-temperature-humidity-coupling-strength" class="level2">
<h2 class="anchored" data-anchor-id="finding-3-height-influences-temperature-humidity-coupling-strength">Finding 3: Height Influences Temperature-Humidity Coupling Strength</h2>
<div id="11c839f0" class="cell" data-execution_count="12">
<details class="code-fold">
<summary>Show Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> plot_temp_vs_humidity_by_height(data, figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">8</span>)):</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="co">    Scatter plot of temperature vs humidity colored by height</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>    fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>figsize)</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>    <span class="co">#sample = data.sample(n=min(5000, len(data)), random_state=42)</span></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>    sample<span class="op">=</span> data</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>    scatter <span class="op">=</span> ax.scatter(sample[<span class="st">'humid_temp'</span>], sample[<span class="st">'humidity'</span>], </span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>                        c<span class="op">=</span>sample[<span class="st">'Height'</span>], cmap<span class="op">=</span><span class="st">'viridis'</span>, </span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>                        alpha<span class="op">=</span><span class="fl">0.6</span>, s<span class="op">=</span><span class="dv">20</span>, edgecolors<span class="op">=</span><span class="st">'none'</span>)</span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>    ax.set_xlabel(<span class="st">'Temperature (°C)'</span>, fontsize<span class="op">=</span><span class="dv">13</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>    ax.set_ylabel(<span class="st">'Relative Humidity (%)'</span>, fontsize<span class="op">=</span><span class="dv">13</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a>    ax.set_title(<span class="st">'Temperature-Humidity Relationship by Canopy Height'</span>, </span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a>                 fontsize<span class="op">=</span><span class="dv">15</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a>    ax.grid(<span class="va">True</span>, alpha<span class="op">=</span><span class="fl">0.3</span>)</span>
<span id="cb19-19"><a href="#cb19-19" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb19-20"><a href="#cb19-20" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Colorbar</span></span>
<span id="cb19-21"><a href="#cb19-21" aria-hidden="true" tabindex="-1"></a>    cbar <span class="op">=</span> plt.colorbar(scatter, ax<span class="op">=</span>ax)</span>
<span id="cb19-22"><a href="#cb19-22" aria-hidden="true" tabindex="-1"></a>    cbar.set_label(<span class="st">'Height Above Ground (m)'</span>, fontsize<span class="op">=</span><span class="dv">12</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb19-23"><a href="#cb19-23" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb19-24"><a href="#cb19-24" aria-hidden="true" tabindex="-1"></a>    plt.tight_layout()</span>
<span id="cb19-25"><a href="#cb19-25" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> fig</span>
<span id="cb19-26"><a href="#cb19-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-27"><a href="#cb19-27" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> plot_temp_vs_humidity_by_height(analysis_data)</span>
<span id="cb19-28"><a href="#cb19-28" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="lab1_python_files/figure-html/cell-13-output-1.png" width="899" height="757" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Relative humidity decreases when temperature increases, showing a clear inverse relationship between these two variables. Point color indicates height above ground, revealing that measurements from higher canopy layers tend to be slightly warmer and drier, while lower layers are cooler and more humid. This pattern highlights a vertical microclimatic gradient within the forest canopy, with lower layers experiencing more moisture and variability, and upper layers being drier and thermally more stable.</p>
</section>
<section id="finding-4-humidity-relationship-with-height" class="level2">
<h2 class="anchored" data-anchor-id="finding-4-humidity-relationship-with-height">Finding 4: Humidity Relationship with Height</h2>
<div id="cell-finding4-humidity-height" class="cell" data-execution_count="13">
<details class="code-fold">
<summary>Show Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> plot_humidity_vs_height(data, figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">7</span>)):</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="co">    Simple scatter plot of humidity vs height</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>    fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>figsize)</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>    sample <span class="op">=</span> data.sample(n<span class="op">=</span><span class="bu">min</span>(<span class="dv">3000</span>, <span class="bu">len</span>(data)), random_state<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>    scatter <span class="op">=</span> ax.scatter(sample[<span class="st">'humidity'</span>], sample[<span class="st">'Height'</span>], </span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>                        c<span class="op">=</span>sample[<span class="st">'humid_temp'</span>], cmap<span class="op">=</span><span class="st">'coolwarm'</span>, </span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>                        alpha<span class="op">=</span><span class="fl">0.5</span>, s<span class="op">=</span><span class="dv">15</span>, edgecolors<span class="op">=</span><span class="st">'none'</span>)</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>    ax.set_xlabel(<span class="st">'Relative Humidity (%)'</span>, fontsize<span class="op">=</span><span class="dv">13</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>    ax.set_ylabel(<span class="st">'Height Above Ground (m)'</span>, fontsize<span class="op">=</span><span class="dv">13</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>    ax.set_title(<span class="st">'Humidity Decreases with Canopy Height'</span>, </span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>                 fontsize<span class="op">=</span><span class="dv">15</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a>    ax.grid(<span class="va">True</span>, alpha<span class="op">=</span><span class="fl">0.3</span>)</span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a>    cbar <span class="op">=</span> plt.colorbar(scatter, ax<span class="op">=</span>ax)</span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a>    cbar.set_label(<span class="st">'Temperature (°C)'</span>, fontsize<span class="op">=</span><span class="dv">12</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a>    plt.tight_layout()</span>
<span id="cb20-21"><a href="#cb20-21" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> fig</span>
<span id="cb20-22"><a href="#cb20-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-23"><a href="#cb20-23" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> plot_humidity_vs_height(analysis_data)</span>
<span id="cb20-24"><a href="#cb20-24" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div id="finding4-humidity-height" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="lab1_python_files/figure-html/finding4-humidity-height-output-1.png" width="730" height="661" class="figure-img"></p>
<figcaption>Relationship between canopy height and relative humidity. Each point represents a single measurement, colored by temperature. The clear downward trend shows that humidity systematically decreases with increasing height above ground.</figcaption>
</figure>
</div>
</div>
</div>
<p>As canopy height increases, relative humidity tends to decrease and temperature tends to cool, reflecting microclimatic changes through the forest vertical structure. Lower layers are warmer and more variable in moisture, while upper layers are cooler and slightly drier.</p>
</section>
<section id="finding-5-humidity-distributions-by-canopy-layer" class="level2">
<h2 class="anchored" data-anchor-id="finding-5-humidity-distributions-by-canopy-layer">Finding 5: Humidity Distributions by Canopy Layer</h2>
<div id="8b879272" class="cell" data-execution_count="14">
<details class="code-fold">
<summary>Show Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> plot_humidity_violins(data, figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">6</span>)):</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="co">    Violin plot of humidity by canancy layer</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>    <span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt  <span class="co"># Move import to TOP</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>    fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>figsize)</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>    layers <span class="op">=</span> [<span class="st">'Lower'</span>, <span class="st">'Middle'</span>, <span class="st">'Upper'</span>]</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>    data_to_plot <span class="op">=</span> [data[data[<span class="st">'canopy_layer'</span>] <span class="op">==</span> layer][<span class="st">'humidity'</span>].dropna().values </span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>                    <span class="cf">for</span> layer <span class="kw">in</span> layers]</span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>    colors <span class="op">=</span> [<span class="st">'forestgreen'</span>, <span class="st">'orange'</span>, <span class="st">'pink'</span>]</span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a>    parts <span class="op">=</span> ax.violinplot(data_to_plot, positions<span class="op">=</span>[<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>], </span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a>                          showmeans<span class="op">=</span><span class="va">True</span>, showmedians<span class="op">=</span><span class="va">True</span>, widths<span class="op">=</span><span class="fl">0.7</span>)</span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> i, pc <span class="kw">in</span> <span class="bu">enumerate</span>(parts[<span class="st">'bodies'</span>]):</span>
<span id="cb21-18"><a href="#cb21-18" aria-hidden="true" tabindex="-1"></a>        pc.set_facecolor(colors[i])</span>
<span id="cb21-19"><a href="#cb21-19" aria-hidden="true" tabindex="-1"></a>        pc.set_alpha(<span class="fl">0.5</span>)</span>
<span id="cb21-20"><a href="#cb21-20" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb21-21"><a href="#cb21-21" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Color the lines</span></span>
<span id="cb21-22"><a href="#cb21-22" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> partname <span class="kw">in</span> (<span class="st">'cbars'</span>, <span class="st">'cmins'</span>, <span class="st">'cmaxes'</span>, <span class="st">'cmedians'</span>, <span class="st">'cmeans'</span>):</span>
<span id="cb21-23"><a href="#cb21-23" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> partname <span class="kw">in</span> parts:</span>
<span id="cb21-24"><a href="#cb21-24" aria-hidden="true" tabindex="-1"></a>            parts[partname].set_edgecolor(<span class="st">'black'</span>)</span>
<span id="cb21-25"><a href="#cb21-25" aria-hidden="true" tabindex="-1"></a>            parts[partname].set_linewidth(<span class="fl">1.5</span>)</span>
<span id="cb21-26"><a href="#cb21-26" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb21-27"><a href="#cb21-27" aria-hidden="true" tabindex="-1"></a>    ax.set_xticks([<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>])</span>
<span id="cb21-28"><a href="#cb21-28" aria-hidden="true" tabindex="-1"></a>    ax.set_xticklabels(layers)</span>
<span id="cb21-29"><a href="#cb21-29" aria-hidden="true" tabindex="-1"></a>    ax.set_xlabel(<span class="st">'Canopy Layer'</span>, fontsize<span class="op">=</span><span class="dv">13</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb21-30"><a href="#cb21-30" aria-hidden="true" tabindex="-1"></a>    ax.set_ylabel(<span class="st">'Relative Humidity (%)'</span>, fontsize<span class="op">=</span><span class="dv">13</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb21-31"><a href="#cb21-31" aria-hidden="true" tabindex="-1"></a>    ax.set_title(<span class="st">'Humidity Distribution by Canopy Layer'</span>, </span>
<span id="cb21-32"><a href="#cb21-32" aria-hidden="true" tabindex="-1"></a>                 fontsize<span class="op">=</span><span class="dv">15</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb21-33"><a href="#cb21-33" aria-hidden="true" tabindex="-1"></a>    ax.grid(<span class="va">True</span>, alpha<span class="op">=</span><span class="fl">0.3</span>, axis<span class="op">=</span><span class="st">'y'</span>)</span>
<span id="cb21-34"><a href="#cb21-34" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb21-35"><a href="#cb21-35" aria-hidden="true" tabindex="-1"></a>    plt.tight_layout()</span>
<span id="cb21-36"><a href="#cb21-36" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> fig</span>
<span id="cb21-37"><a href="#cb21-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-38"><a href="#cb21-38" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> plot_humidity_violins(analysis_data)</span>
<span id="cb21-39"><a href="#cb21-39" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="lab1_python_files/figure-html/cell-15-output-1.png" width="757" height="565" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Median humidity values are similar across layers, approximately 55–60%, indicating that typical humidity is consistent throughout the canopy. However, the distribution shapes reveal layer-specific variability. The Lower and Middle layers exhibit wider spreads at low humidity values, suggesting that these layers experience more frequent dry conditions. In contrast, the Upper layer shows a slightly narrower distribution around the median, with fewer extremely low values, though it still reaches high humidity levels. Overall, while central tendencies are similar, the lower and middle canopy layers are subject to greater fluctuations in relative humidity, likely reflecting microclimatic effects such as differential sunlight exposure and airflow.</p>
</section>
</section>
<section id="discussion" class="level1">
<h1>Discussion</h1>
<p>This analysis demonstrates that temperature-humidity relationships in redwood canopies vary systematically with vertical position, revealing fundamentally different environmental processes operating at different heights. The three key findings tell a coherent story about canopy microclimate structure:</p>
<p>The strength of temperature-humidity coupling increases with height. Upper canopy sensors show tight inverse relationships characteristic of direct atmospheric forcing, while lower canopy sensors show weak, diffuse relationships indicating buffering and decoupling from atmospheric conditions. This gradient in coupling strength reflects the transition from exposed, atmosphere-dominated conditions at the top to buffered, tree-physiology-influenced conditions at the bottom.</p>
<p>Second, despite dramatic differences in light exposure and humidity levels, temperature remains relatively uniform across canopy heights. This thermal uniformity, combined with varying humidity, creates distinct microenvironments: the upper canopy is warm and dry while the lower canopy is warm and humid. The combination of similar temperatures but different humidities means that vapor pressure deficit (the driving force for transpiration) varies substantially with height even though temperature alone would suggest similar conditions.</p>
<p>From a tree physiology perspective, these findings have important implications. The upper canopy operates under high evaporative demand (low humidity) despite moderate temperatures, requiring substantial water transport from roots. The tight temperature-humidity coupling means that upper leaves experience coordinated stress from both factors. The lower canopy benefits from high humidity reducing water stress, and the weak temperature-humidity coupling means that fog events can raise humidity independent of temperature changes, providing additional moisture without requiring temperature drops.</p>
<p>These patterns also highlight the limitations of using temperature alone as a microclimate indicator. Two positions with identical temperatures (as seen in Finding 2) can have dramatically different humidity levels and different environmental forcing mechanisms (as seen in Findings 1 and 3). A complete understanding of canopy microclimate requires examining multiple variables and their relationships, not just their individual distributions.</p>
<p>Future work could examine how these temperature-humidity relationships vary diurnally (day versus night), seasonally, or during specific weather events like fog intrusions or heat waves. Comparing multiple trees or forest stands would test whether these patterns are general features of tall forest canopies or specific to this particular redwood tree and its coastal location.</p>
<!-- -->

</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb22" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Lab 1 - Redwood Trees: Temperature-Humidity Relationships Across Diffrent Canopy Heights"</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Rihanna Razavi"</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span><span class="co"> </span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: true</span></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a><span class="co">    code-summary: "Show Code"</span></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a><span class="co">    theme: sandstone</span></span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a><span class="an">jupyter:</span><span class="co"> python3</span></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a><span class="an">toc:</span><span class="co"> true</span></span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a><span class="an">execute:</span><span class="co"> </span></span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a><span class="co">  warning: false</span></span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a><span class="co">  message: false</span></span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: setup</span></span>
<span id="cb22-20"><a href="#cb22-20" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> sys</span>
<span id="cb22-21"><a href="#cb22-21" aria-hidden="true" tabindex="-1"></a>sys.path.append(<span class="st">".."</span>)</span>
<span id="cb22-22"><a href="#cb22-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-23"><a href="#cb22-23" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb22-24"><a href="#cb22-24" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb22-25"><a href="#cb22-25" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb22-26"><a href="#cb22-26" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb22-27"><a href="#cb22-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-28"><a href="#cb22-28" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> os.path <span class="im">import</span> join <span class="im">as</span> oj</span>
<span id="cb22-29"><a href="#cb22-29" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> python.load <span class="im">import</span> load_dates_data, load_mote_location_data, load_redwood_data</span>
<span id="cb22-30"><a href="#cb22-30" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> python.clean <span class="im">import</span> clean_dates_data, clean_mote_location_data, clean_redwood_data</span>
<span id="cb22-31"><a href="#cb22-31" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> python.prepare <span class="im">import</span> prepare_analysis_data</span>
<span id="cb22-32"><a href="#cb22-32" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> python.stats <span class="im">import</span> calculate_data_quality_metrics</span>
<span id="cb22-33"><a href="#cb22-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-34"><a href="#cb22-34" aria-hidden="true" tabindex="-1"></a>DATA_PATH <span class="op">=</span> oj(<span class="st">".."</span>, <span class="st">"data"</span>)</span>
<span id="cb22-35"><a href="#cb22-35" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb22-36"><a href="#cb22-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-37"><a href="#cb22-37" aria-hidden="true" tabindex="-1"></a><span class="fu"># Introduction</span></span>
<span id="cb22-38"><a href="#cb22-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-39"><a href="#cb22-39" aria-hidden="true" tabindex="-1"></a>Understanding how environmental conditions vary in forest canopies is essential for predicting tree physiology, carbon cycling, and ecosystem responses to climate change. Temperature and humidity are fundamental drivers of photosynthesis and transpiration in trees, yet their interactions within tall forest canopies remain poorly understood due to the difficulty of measuring these variables at multiple heights all together.</span>
<span id="cb22-40"><a href="#cb22-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-41"><a href="#cb22-41" aria-hidden="true" tabindex="-1"></a>Coastal redwood (*Sequoia sempervirens*) trees create complex microclimates due to their extreme height (often exceeding 70 meters) and dense canopy structure. Traditional ecological theory suggests that upper canopy positions should be hotter and drier due to direct solar exposure, while lower canopy positions should be cooler and more humid. However, the actual temperature-humidity relationships at different canopy heights, and how these relationships reflect different environmental processes, have rarely been quantified at fine spatial scales.</span>
<span id="cb22-42"><a href="#cb22-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-43"><a href="#cb22-43" aria-hidden="true" tabindex="-1"></a>**Research Question:** How does the relationship between temperature and humidity vary across different vertical positions within a coastal redwood canopy? </span>
<span id="cb22-44"><a href="#cb22-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-45"><a href="#cb22-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-46"><a href="#cb22-46" aria-hidden="true" tabindex="-1"></a>This analysis uses high-resolution sensor network data from Tolle et al. (2005) collected over 44 days in a single redwood tree to examine how temperature-humidity relationships differ between lower, middle, and upper canopy positions.</span>
<span id="cb22-47"><a href="#cb22-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-48"><a href="#cb22-48" aria-hidden="true" tabindex="-1"></a><span class="fu"># Data Overview and Collection</span></span>
<span id="cb22-51"><a href="#cb22-51" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb22-52"><a href="#cb22-52" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: load-data</span></span>
<span id="cb22-53"><a href="#cb22-53" aria-hidden="true" tabindex="-1"></a><span class="co"># Load individual datasets</span></span>
<span id="cb22-54"><a href="#cb22-54" aria-hidden="true" tabindex="-1"></a>dates_orig <span class="op">=</span> load_dates_data(DATA_PATH)</span>
<span id="cb22-55"><a href="#cb22-55" aria-hidden="true" tabindex="-1"></a>motes_orig <span class="op">=</span> load_mote_location_data(DATA_PATH)</span>
<span id="cb22-56"><a href="#cb22-56" aria-hidden="true" tabindex="-1"></a>redwood_net_orig <span class="op">=</span> load_redwood_data(DATA_PATH, source<span class="op">=</span><span class="st">"net"</span>)</span>
<span id="cb22-57"><a href="#cb22-57" aria-hidden="true" tabindex="-1"></a>redwood_log_orig <span class="op">=</span> load_redwood_data(DATA_PATH, source<span class="op">=</span><span class="st">"log"</span>)</span>
<span id="cb22-58"><a href="#cb22-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-59"><a href="#cb22-59" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"=== ORIGINAL DATASETS ==="</span>)</span>
<span id="cb22-60"><a href="#cb22-60" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Network dataset: </span><span class="sc">{</span><span class="bu">len</span>(redwood_net_orig)<span class="sc">:,}</span><span class="ss"> observations"</span>)</span>
<span id="cb22-61"><a href="#cb22-61" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Log dataset: </span><span class="sc">{</span><span class="bu">len</span>(redwood_log_orig)<span class="sc">:,}</span><span class="ss"> observations"</span>)</span>
<span id="cb22-62"><a href="#cb22-62" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Number of unique sensors (net): </span><span class="sc">{</span>redwood_net_orig[<span class="st">'nodeid'</span>]<span class="sc">.</span>nunique()<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb22-63"><a href="#cb22-63" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Number of unique sensors (log): </span><span class="sc">{</span>redwood_log_orig[<span class="st">'nodeid'</span>]<span class="sc">.</span>nunique()<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb22-64"><a href="#cb22-64" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb22-65"><a href="#cb22-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-66"><a href="#cb22-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-67"><a href="#cb22-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-68"><a href="#cb22-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-69"><a href="#cb22-69" aria-hidden="true" tabindex="-1"></a><span class="fu"># Data Cleaning</span></span>
<span id="cb22-70"><a href="#cb22-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-71"><a href="#cb22-71" aria-hidden="true" tabindex="-1"></a><span class="fu">## Step 1: Load Datasets and Examine Voltage Distributions</span></span>
<span id="cb22-74"><a href="#cb22-74" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb22-75"><a href="#cb22-75" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: load-datasets</span></span>
<span id="cb22-76"><a href="#cb22-76" aria-hidden="true" tabindex="-1"></a><span class="co"># Load net and log datasets separately</span></span>
<span id="cb22-77"><a href="#cb22-77" aria-hidden="true" tabindex="-1"></a>redwood_net_orig <span class="op">=</span> load_redwood_data(DATA_PATH, source<span class="op">=</span><span class="st">"net"</span>)</span>
<span id="cb22-78"><a href="#cb22-78" aria-hidden="true" tabindex="-1"></a>redwood_log_orig <span class="op">=</span> load_redwood_data(DATA_PATH, source<span class="op">=</span><span class="st">"log"</span>)</span>
<span id="cb22-79"><a href="#cb22-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-80"><a href="#cb22-80" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"=== ORIGINAL DATASETS ==="</span>)</span>
<span id="cb22-81"><a href="#cb22-81" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Network dataset: </span><span class="sc">{</span><span class="bu">len</span>(redwood_net_orig)<span class="sc">:,}</span><span class="ss"> observations"</span>)</span>
<span id="cb22-82"><a href="#cb22-82" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Log dataset: </span><span class="sc">{</span><span class="bu">len</span>(redwood_log_orig)<span class="sc">:,}</span><span class="ss"> observations"</span>)</span>
<span id="cb22-83"><a href="#cb22-83" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-84"><a href="#cb22-84" aria-hidden="true" tabindex="-1"></a>net_voltage_mean <span class="op">=</span> redwood_net_orig[<span class="st">'voltage'</span>].mean()</span>
<span id="cb22-85"><a href="#cb22-85" aria-hidden="true" tabindex="-1"></a>log_voltage_mean <span class="op">=</span> redwood_log_orig[<span class="st">'voltage'</span>].mean()</span>
<span id="cb22-86"><a href="#cb22-86" aria-hidden="true" tabindex="-1"></a>net_voltage_max <span class="op">=</span> redwood_net_orig[<span class="st">'voltage'</span>].<span class="bu">max</span>()</span>
<span id="cb22-87"><a href="#cb22-87" aria-hidden="true" tabindex="-1"></a>log_voltage_max <span class="op">=</span> redwood_log_orig[<span class="st">'voltage'</span>].<span class="bu">max</span>()</span>
<span id="cb22-88"><a href="#cb22-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-89"><a href="#cb22-89" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">Net voltage: mean=</span><span class="sc">{</span>net_voltage_mean<span class="sc">:.2f}</span><span class="ss">, max=</span><span class="sc">{</span>net_voltage_max<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb22-90"><a href="#cb22-90" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Log voltage: mean=</span><span class="sc">{</span>log_voltage_mean<span class="sc">:.2f}</span><span class="ss">, max=</span><span class="sc">{</span>log_voltage_max<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb22-91"><a href="#cb22-91" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-92"><a href="#cb22-92" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> net_voltage_max <span class="op">&gt;</span> <span class="dv">100</span> <span class="kw">and</span> log_voltage_max <span class="op">&lt;</span> <span class="dv">10</span>:</span>
<span id="cb22-93"><a href="#cb22-93" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"Net dataset: Raw ADC values (0-1023)"</span>)</span>
<span id="cb22-94"><a href="#cb22-94" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"Log dataset: Actual voltages (0-3.3V)"</span>)</span>
<span id="cb22-95"><a href="#cb22-95" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"These need to be aligned before merging!"</span>)</span>
<span id="cb22-96"><a href="#cb22-96" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb22-97"><a href="#cb22-97" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-98"><a href="#cb22-98" aria-hidden="true" tabindex="-1"></a><span class="fu">## Step 2: Empirical Voltage Calibration</span></span>
<span id="cb22-101"><a href="#cb22-101" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb22-102"><a href="#cb22-102" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> python.clean <span class="im">import</span> find_empirical_voltage_conversion</span>
<span id="cb22-103"><a href="#cb22-103" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-104"><a href="#cb22-104" aria-hidden="true" tabindex="-1"></a><span class="co"># Finding empirical conversion by matching distributions</span></span>
<span id="cb22-105"><a href="#cb22-105" aria-hidden="true" tabindex="-1"></a><span class="co">#it's a heuristic common approach</span></span>
<span id="cb22-106"><a href="#cb22-106" aria-hidden="true" tabindex="-1"></a>conversion_factor, conversion_offset, calibration_fig <span class="op">=</span> find_empirical_voltage_conversion(</span>
<span id="cb22-107"><a href="#cb22-107" aria-hidden="true" tabindex="-1"></a>    redwood_net_orig,</span>
<span id="cb22-108"><a href="#cb22-108" aria-hidden="true" tabindex="-1"></a>    redwood_log_orig</span>
<span id="cb22-109"><a href="#cb22-109" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb22-110"><a href="#cb22-110" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-111"><a href="#cb22-111" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss"> EMPIRICAL CONVERSION FORMULA:"</span>)</span>
<span id="cb22-112"><a href="#cb22-112" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"   V_corrected = </span><span class="sc">{</span>conversion_factor<span class="sc">:.6f}</span><span class="ss"> × V_net + </span><span class="sc">{</span>conversion_offset<span class="sc">:.6f}</span><span class="ss">"</span>)</span>
<span id="cb22-113"><a href="#cb22-113" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb22-116"><a href="#cb22-116" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb22-117"><a href="#cb22-117" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: calibration-plot</span></span>
<span id="cb22-118"><a href="#cb22-118" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Empirical voltage calibration by matching distribution percentiles across log and net (My own idea). Top row: original distributions and percentile-based linear fit showing how to align them. Bottom row: distributions after conversion with overlay (left), valid range zoom (middle), and Q-Q plot confirming alignment (right)."</span></span>
<span id="cb22-119"><a href="#cb22-119" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-120"><a href="#cb22-120" aria-hidden="true" tabindex="-1"></a>plt.figure(calibration_fig.number)</span>
<span id="cb22-121"><a href="#cb22-121" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb22-122"><a href="#cb22-122" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb22-123"><a href="#cb22-123" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-124"><a href="#cb22-124" aria-hidden="true" tabindex="-1"></a>Rather than relying on theoretical conversion formulas that may not reflect the actual hardware configuration, we use an empirical approach to align the voltage distributions. We match the 25th, 50th, and 75th percentiles between the Net and Log datasets to find a linear transformation (scale + offset) that makes the distributions align. This data-driven method accounts for any calibration differences, reference voltage variations, or systematic offsets between the two data collection systems.</span>
<span id="cb22-125"><a href="#cb22-125" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-126"><a href="#cb22-126" aria-hidden="true" tabindex="-1"></a><span class="fu">## Step 3: Apply Conversion and Merge Datasets</span></span>
<span id="cb22-129"><a href="#cb22-129" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb22-130"><a href="#cb22-130" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: apply-conversion-merge</span></span>
<span id="cb22-131"><a href="#cb22-131" aria-hidden="true" tabindex="-1"></a><span class="co"># Apply empirical conversion to net dataset</span></span>
<span id="cb22-132"><a href="#cb22-132" aria-hidden="true" tabindex="-1"></a>redwood_net_converted <span class="op">=</span> redwood_net_orig.copy()</span>
<span id="cb22-133"><a href="#cb22-133" aria-hidden="true" tabindex="-1"></a>redwood_net_converted[<span class="st">'voltage'</span>] <span class="op">=</span> (redwood_net_orig[<span class="st">'voltage'</span>] <span class="op">*</span> conversion_factor <span class="op">+</span> conversion_offset)</span>
<span id="cb22-134"><a href="#cb22-134" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-135"><a href="#cb22-135" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"=== VOLTAGE AFTER EMPIRICAL CONVERSION ==="</span>)</span>
<span id="cb22-136"><a href="#cb22-136" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Net converted: mean=</span><span class="sc">{</span>redwood_net_converted[<span class="st">'voltage'</span>]<span class="sc">.</span>mean()<span class="sc">:.2f}</span><span class="ss">V, range=[</span><span class="sc">{</span>redwood_net_converted[<span class="st">'voltage'</span>]<span class="sc">.</span><span class="bu">min</span>()<span class="sc">:.2f}</span><span class="ss">, </span><span class="sc">{</span>redwood_net_converted[<span class="st">'voltage'</span>]<span class="sc">.</span><span class="bu">max</span>()<span class="sc">:.2f}</span><span class="ss">]"</span>)</span>
<span id="cb22-137"><a href="#cb22-137" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Log original:  mean=</span><span class="sc">{</span>redwood_log_orig[<span class="st">'voltage'</span>]<span class="sc">.</span>mean()<span class="sc">:.2f}</span><span class="ss">V, range=[</span><span class="sc">{</span>redwood_log_orig[<span class="st">'voltage'</span>]<span class="sc">.</span><span class="bu">min</span>()<span class="sc">:.2f}</span><span class="ss">, </span><span class="sc">{</span>redwood_log_orig[<span class="st">'voltage'</span>]<span class="sc">.</span><span class="bu">max</span>()<span class="sc">:.2f}</span><span class="ss">]"</span>)</span>
<span id="cb22-138"><a href="#cb22-138" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Mean difference after conversion: </span><span class="sc">{</span><span class="bu">abs</span>(redwood_net_converted[<span class="st">'voltage'</span>].mean() <span class="op">-</span> redwood_log_orig[<span class="st">'voltage'</span>].mean())<span class="sc">:.3f}</span><span class="ss">V"</span>)</span>
<span id="cb22-139"><a href="#cb22-139" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-140"><a href="#cb22-140" aria-hidden="true" tabindex="-1"></a>redwood_net_converted[<span class="st">'source'</span>] <span class="op">=</span> <span class="st">'net'</span></span>
<span id="cb22-141"><a href="#cb22-141" aria-hidden="true" tabindex="-1"></a>redwood_log_orig[<span class="st">'source'</span>] <span class="op">=</span> <span class="st">'log'</span></span>
<span id="cb22-142"><a href="#cb22-142" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-143"><a href="#cb22-143" aria-hidden="true" tabindex="-1"></a>redwood_merged <span class="op">=</span> pd.concat([redwood_net_converted, redwood_log_orig], ignore_index<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb22-144"><a href="#cb22-144" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Before removing duplicates: </span><span class="sc">{</span><span class="bu">len</span>(redwood_merged)<span class="sc">:,}</span><span class="ss">"</span>)</span>
<span id="cb22-145"><a href="#cb22-145" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-146"><a href="#cb22-146" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove duplicates (same sensor, same time, same measurement period)</span></span>
<span id="cb22-147"><a href="#cb22-147" aria-hidden="true" tabindex="-1"></a>redwood_merged <span class="op">=</span> redwood_merged.drop_duplicates(</span>
<span id="cb22-148"><a href="#cb22-148" aria-hidden="true" tabindex="-1"></a>    subset<span class="op">=</span>[<span class="st">'nodeid'</span>, <span class="st">'result_time'</span>, <span class="st">'epoch'</span>],</span>
<span id="cb22-149"><a href="#cb22-149" aria-hidden="true" tabindex="-1"></a>    keep<span class="op">=</span><span class="st">'first'</span></span>
<span id="cb22-150"><a href="#cb22-150" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb22-151"><a href="#cb22-151" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-152"><a href="#cb22-152" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"After removing duplicates: </span><span class="sc">{</span><span class="bu">len</span>(redwood_merged)<span class="sc">:,}</span><span class="ss">"</span>)</span>
<span id="cb22-153"><a href="#cb22-153" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">Merged voltage statistics:"</span>)</span>
<span id="cb22-154"><a href="#cb22-154" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  Mean: </span><span class="sc">{</span>redwood_merged[<span class="st">'voltage'</span>]<span class="sc">.</span>mean()<span class="sc">:.2f}</span><span class="ss">V"</span>)</span>
<span id="cb22-155"><a href="#cb22-155" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  Min: </span><span class="sc">{</span>redwood_merged[<span class="st">'voltage'</span>]<span class="sc">.</span><span class="bu">min</span>()<span class="sc">:.2f}</span><span class="ss">V"</span>)</span>
<span id="cb22-156"><a href="#cb22-156" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  Max: </span><span class="sc">{</span>redwood_merged[<span class="st">'voltage'</span>]<span class="sc">.</span><span class="bu">max</span>()<span class="sc">:.2f}</span><span class="ss">V"</span>)</span>
<span id="cb22-157"><a href="#cb22-157" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb22-158"><a href="#cb22-158" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-159"><a href="#cb22-159" aria-hidden="true" tabindex="-1"></a><span class="fu">## Step 4: Clean the Merged Dataset</span></span>
<span id="cb22-162"><a href="#cb22-162" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb22-163"><a href="#cb22-163" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> python.clean <span class="im">import</span> clean_redwood_data, clean_dates_data, clean_mote_location_data</span>
<span id="cb22-164"><a href="#cb22-164" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-165"><a href="#cb22-165" aria-hidden="true" tabindex="-1"></a>dates_df <span class="op">=</span> clean_dates_data(dates_orig)</span>
<span id="cb22-166"><a href="#cb22-166" aria-hidden="true" tabindex="-1"></a>motes_df <span class="op">=</span> clean_mote_location_data(motes_orig)</span>
<span id="cb22-167"><a href="#cb22-167" aria-hidden="true" tabindex="-1"></a>redwood_all_df <span class="op">=</span> clean_redwood_data(redwood_merged)</span>
<span id="cb22-168"><a href="#cb22-168" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-169"><a href="#cb22-169" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate metrics</span></span>
<span id="cb22-170"><a href="#cb22-170" aria-hidden="true" tabindex="-1"></a>quality_metrics <span class="op">=</span> calculate_data_quality_metrics(redwood_merged, redwood_all_df)</span>
<span id="cb22-171"><a href="#cb22-171" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-172"><a href="#cb22-172" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"=== DATA CLEANING SUMMARY ==="</span>)</span>
<span id="cb22-173"><a href="#cb22-173" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Original (merged): </span><span class="sc">{</span>quality_metrics[<span class="st">'original_rows'</span>]<span class="sc">:,}</span><span class="ss">"</span>)</span>
<span id="cb22-174"><a href="#cb22-174" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Cleaned: </span><span class="sc">{</span>quality_metrics[<span class="st">'cleaned_rows'</span>]<span class="sc">:,}</span><span class="ss">"</span>)</span>
<span id="cb22-175"><a href="#cb22-175" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Removed: </span><span class="sc">{</span>quality_metrics[<span class="st">'removed_rows'</span>]<span class="sc">:,}</span><span class="ss"> (</span><span class="sc">{</span><span class="dv">100</span> <span class="op">-</span> quality_metrics[<span class="st">'retention_pct'</span>]<span class="sc">:.1f}</span><span class="ss">%)"</span>)</span>
<span id="cb22-176"><a href="#cb22-176" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Retention: </span><span class="sc">{</span>quality_metrics[<span class="st">'retention_pct'</span>]<span class="sc">:.1f}</span><span class="ss">%"</span>)</span>
<span id="cb22-177"><a href="#cb22-177" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-178"><a href="#cb22-178" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">Cleaned voltage statistics:"</span>)</span>
<span id="cb22-179"><a href="#cb22-179" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  Mean: </span><span class="sc">{</span>redwood_all_df[<span class="st">'voltage'</span>]<span class="sc">.</span>mean()<span class="sc">:.2f}</span><span class="ss">V"</span>)</span>
<span id="cb22-180"><a href="#cb22-180" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  Min: </span><span class="sc">{</span>redwood_all_df[<span class="st">'voltage'</span>]<span class="sc">.</span><span class="bu">min</span>()<span class="sc">:.2f}</span><span class="ss">V"</span>)</span>
<span id="cb22-181"><a href="#cb22-181" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  Max: </span><span class="sc">{</span>redwood_all_df[<span class="st">'voltage'</span>]<span class="sc">.</span><span class="bu">max</span>()<span class="sc">:.2f}</span><span class="ss">V"</span>)</span>
<span id="cb22-182"><a href="#cb22-182" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb22-185"><a href="#cb22-185" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb22-186"><a href="#cb22-186" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: voltage-before-after</span></span>
<span id="cb22-187"><a href="#cb22-187" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Voltage distribution before and after cleaning. Left: merged data after empirical conversion but before quality filtering shows the full range. Right: after removing invalid readings (outside 0-4V range) and other quality filters, retaining only reliable measurements."</span></span>
<span id="cb22-188"><a href="#cb22-188" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-189"><a href="#cb22-189" aria-hidden="true" tabindex="-1"></a>fig, (ax1, ax2) <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">14</span>, <span class="dv">5</span>))</span>
<span id="cb22-190"><a href="#cb22-190" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-191"><a href="#cb22-191" aria-hidden="true" tabindex="-1"></a><span class="co"># Before cleaning</span></span>
<span id="cb22-192"><a href="#cb22-192" aria-hidden="true" tabindex="-1"></a>ax1.hist(redwood_merged[<span class="st">'voltage'</span>].dropna(), bins<span class="op">=</span><span class="dv">50</span>, alpha<span class="op">=</span><span class="fl">0.7</span>,</span>
<span id="cb22-193"><a href="#cb22-193" aria-hidden="true" tabindex="-1"></a>        color<span class="op">=</span><span class="st">'orange'</span>, edgecolor<span class="op">=</span><span class="st">'darkorange'</span>)</span>
<span id="cb22-194"><a href="#cb22-194" aria-hidden="true" tabindex="-1"></a>ax1.axvline(<span class="dv">0</span>, color<span class="op">=</span><span class="st">'red'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>, linewidth<span class="op">=</span><span class="dv">2</span>, label<span class="op">=</span><span class="st">'Valid range'</span>)</span>
<span id="cb22-195"><a href="#cb22-195" aria-hidden="true" tabindex="-1"></a>ax1.axvline(<span class="dv">4</span>, color<span class="op">=</span><span class="st">'red'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>, linewidth<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb22-196"><a href="#cb22-196" aria-hidden="true" tabindex="-1"></a>ax1.axvline(<span class="fl">2.4</span>, color<span class="op">=</span><span class="st">'green'</span>, linestyle<span class="op">=</span><span class="st">':'</span>, linewidth<span class="op">=</span><span class="fl">1.5</span>, alpha<span class="op">=</span><span class="fl">0.7</span>, label<span class="op">=</span><span class="st">'Typical range'</span>)</span>
<span id="cb22-197"><a href="#cb22-197" aria-hidden="true" tabindex="-1"></a>ax1.axvline(<span class="fl">3.0</span>, color<span class="op">=</span><span class="st">'green'</span>, linestyle<span class="op">=</span><span class="st">':'</span>, linewidth<span class="op">=</span><span class="fl">1.5</span>, alpha<span class="op">=</span><span class="fl">0.7</span>)</span>
<span id="cb22-198"><a href="#cb22-198" aria-hidden="true" tabindex="-1"></a>ax1.set_xlabel(<span class="st">'Voltage (V)'</span>, fontsize<span class="op">=</span><span class="dv">12</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb22-199"><a href="#cb22-199" aria-hidden="true" tabindex="-1"></a>ax1.set_ylabel(<span class="st">'Frequency'</span>, fontsize<span class="op">=</span><span class="dv">12</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb22-200"><a href="#cb22-200" aria-hidden="true" tabindex="-1"></a>ax1.set_title(<span class="ss">f'Before Cleaning</span><span class="ch">\n</span><span class="ss">n = </span><span class="sc">{</span><span class="bu">len</span>(redwood_merged)<span class="sc">:,}</span><span class="ss">'</span>, fontsize<span class="op">=</span><span class="dv">14</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb22-201"><a href="#cb22-201" aria-hidden="true" tabindex="-1"></a>ax1.legend()</span>
<span id="cb22-202"><a href="#cb22-202" aria-hidden="true" tabindex="-1"></a>ax1.grid(<span class="va">True</span>, alpha<span class="op">=</span><span class="fl">0.3</span>)</span>
<span id="cb22-203"><a href="#cb22-203" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-204"><a href="#cb22-204" aria-hidden="true" tabindex="-1"></a><span class="co"># After cleaning</span></span>
<span id="cb22-205"><a href="#cb22-205" aria-hidden="true" tabindex="-1"></a>ax2.hist(redwood_all_df[<span class="st">'voltage'</span>].dropna(), bins<span class="op">=</span><span class="dv">50</span>, alpha<span class="op">=</span><span class="fl">0.7</span>,</span>
<span id="cb22-206"><a href="#cb22-206" aria-hidden="true" tabindex="-1"></a>        color<span class="op">=</span><span class="st">'green'</span>, edgecolor<span class="op">=</span><span class="st">'darkgreen'</span>)</span>
<span id="cb22-207"><a href="#cb22-207" aria-hidden="true" tabindex="-1"></a>ax2.axvline(<span class="dv">0</span>, color<span class="op">=</span><span class="st">'red'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>, linewidth<span class="op">=</span><span class="dv">2</span>, label<span class="op">=</span><span class="st">'Valid range'</span>)</span>
<span id="cb22-208"><a href="#cb22-208" aria-hidden="true" tabindex="-1"></a>ax2.axvline(<span class="dv">4</span>, color<span class="op">=</span><span class="st">'red'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>, linewidth<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb22-209"><a href="#cb22-209" aria-hidden="true" tabindex="-1"></a>ax2.axvline(<span class="fl">2.4</span>, color<span class="op">=</span><span class="st">'blue'</span>, linestyle<span class="op">=</span><span class="st">':'</span>, linewidth<span class="op">=</span><span class="fl">1.5</span>, alpha<span class="op">=</span><span class="fl">0.7</span>, label<span class="op">=</span><span class="st">'Typical range'</span>)</span>
<span id="cb22-210"><a href="#cb22-210" aria-hidden="true" tabindex="-1"></a>ax2.axvline(<span class="fl">3.0</span>, color<span class="op">=</span><span class="st">'blue'</span>, linestyle<span class="op">=</span><span class="st">':'</span>, linewidth<span class="op">=</span><span class="fl">1.5</span>, alpha<span class="op">=</span><span class="fl">0.7</span>)</span>
<span id="cb22-211"><a href="#cb22-211" aria-hidden="true" tabindex="-1"></a>ax2.set_xlabel(<span class="st">'Voltage (V)'</span>, fontsize<span class="op">=</span><span class="dv">12</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb22-212"><a href="#cb22-212" aria-hidden="true" tabindex="-1"></a>ax2.set_ylabel(<span class="st">'Frequency'</span>, fontsize<span class="op">=</span><span class="dv">12</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb22-213"><a href="#cb22-213" aria-hidden="true" tabindex="-1"></a>ax2.set_title(<span class="ss">f'After Cleaning</span><span class="ch">\n</span><span class="ss">n = </span><span class="sc">{</span><span class="bu">len</span>(redwood_all_df)<span class="sc">:,}</span><span class="ss">'</span>, fontsize<span class="op">=</span><span class="dv">14</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb22-214"><a href="#cb22-214" aria-hidden="true" tabindex="-1"></a>ax2.legend()</span>
<span id="cb22-215"><a href="#cb22-215" aria-hidden="true" tabindex="-1"></a>ax2.grid(<span class="va">True</span>, alpha<span class="op">=</span><span class="fl">0.3</span>)</span>
<span id="cb22-216"><a href="#cb22-216" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-217"><a href="#cb22-217" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb22-218"><a href="#cb22-218" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb22-219"><a href="#cb22-219" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb22-220"><a href="#cb22-220" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-221"><a href="#cb22-221" aria-hidden="true" tabindex="-1"></a><span class="fu">## Data Quality Issues and Cleaning Procedures</span></span>
<span id="cb22-222"><a href="#cb22-222" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-223"><a href="#cb22-223" aria-hidden="true" tabindex="-1"></a>Through systematic examination, we identified several critical data quality issues:</span>
<span id="cb22-224"><a href="#cb22-224" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-225"><a href="#cb22-225" aria-hidden="true" tabindex="-1"></a><span class="fu">### 1. Voltage Scale Inconsistency</span></span>
<span id="cb22-226"><a href="#cb22-226" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-227"><a href="#cb22-227" aria-hidden="true" tabindex="-1"></a>The network and log datasets recorded voltage in fundamentally different scales. The network dataset used raw ADC (analog-to-digital converter) values ranging from 0-1023, while the log dataset stored actual voltages in the 0-3.3V range. Simply merging these datasets would create artificial patterns and invalidate any voltage-based quality filtering.</span>
<span id="cb22-228"><a href="#cb22-228" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-229"><a href="#cb22-229" aria-hidden="true" tabindex="-1"></a>Rather than applying a theoretical conversion formula (which assumes knowledge of the exact reference voltage and ADC configuration),I used an empirical calibration approach. We matched the statistical distributions of the two datasets by finding the linear transformation (scale factor and offset) that aligns their percentiles. </span>
<span id="cb22-230"><a href="#cb22-230" aria-hidden="true" tabindex="-1"></a> V_corrected = 0.016291 × V_net + -0.926464</span>
<span id="cb22-231"><a href="#cb22-231" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-232"><a href="#cb22-232" aria-hidden="true" tabindex="-1"></a><span class="fu">### 2. Invalid Voltage Readings</span></span>
<span id="cb22-233"><a href="#cb22-233" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-234"><a href="#cb22-234" aria-hidden="true" tabindex="-1"></a>We filtered data to retain only readings with voltage between 0-4V. While the typical operating range for these sensors is 2.4-3.0V (shown as dotted green/blue lines in the plots). Values outside 0-4V represent sensor malfunctions or data corruption.</span>
<span id="cb22-235"><a href="#cb22-235" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-236"><a href="#cb22-236" aria-hidden="true" tabindex="-1"></a><span class="fu">### 3. Impossible Physical Values</span></span>
<span id="cb22-237"><a href="#cb22-237" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-238"><a href="#cb22-238" aria-hidden="true" tabindex="-1"></a>We removed readings that violated physical constraints:</span>
<span id="cb22-239"><a href="#cb22-239" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Humidity outside 0-100% (relative humidity cannot exceed saturation or be negative)</span>
<span id="cb22-240"><a href="#cb22-240" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Temperature outside -20°C to 50°C (far outside the range possible in coastal California)</span>
<span id="cb22-241"><a href="#cb22-241" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Negative PAR values (light intensity cannot be negative)</span>
<span id="cb22-242"><a href="#cb22-242" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-243"><a href="#cb22-243" aria-hidden="true" tabindex="-1"></a><span class="fu">### 4. Duplicate Measurements</span></span>
<span id="cb22-244"><a href="#cb22-244" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-245"><a href="#cb22-245" aria-hidden="true" tabindex="-1"></a>After merging the network and log datasets, some measurements appeared twice. We removed duplicates by identifying measurements with matching sensor ID, timestamp, and measurement period, keeping only the first occurrence. </span>
<span id="cb22-246"><a href="#cb22-246" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-247"><a href="#cb22-247" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-248"><a href="#cb22-248" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-249"><a href="#cb22-249" aria-hidden="true" tabindex="-1"></a><span class="fu"># Exploratory Data Analysis</span></span>
<span id="cb22-252"><a href="#cb22-252" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb22-253"><a href="#cb22-253" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: prepare-analysis</span></span>
<span id="cb22-254"><a href="#cb22-254" aria-hidden="true" tabindex="-1"></a><span class="co"># Prepare analysis-ready dataset with canopy layers</span></span>
<span id="cb22-255"><a href="#cb22-255" aria-hidden="true" tabindex="-1"></a>analysis_data <span class="op">=</span> prepare_analysis_data(redwood_all_df, motes_df)</span>
<span id="cb22-256"><a href="#cb22-256" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-257"><a href="#cb22-257" aria-hidden="true" tabindex="-1"></a><span class="co"># Display layer statistics</span></span>
<span id="cb22-258"><a href="#cb22-258" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"=== OBSERVATIONS BY CANOPY LAYER ==="</span>)</span>
<span id="cb22-259"><a href="#cb22-259" aria-hidden="true" tabindex="-1"></a>layer_counts <span class="op">=</span> analysis_data.groupby(<span class="st">'canopy_layer'</span>).size()</span>
<span id="cb22-260"><a href="#cb22-260" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> layer <span class="kw">in</span> [<span class="st">'Lower'</span>, <span class="st">'Middle'</span>, <span class="st">'Upper'</span>]:</span>
<span id="cb22-261"><a href="#cb22-261" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>layer<span class="sc">}</span><span class="ss"> canopy: </span><span class="sc">{</span>layer_counts[layer]<span class="sc">:,}</span><span class="ss"> observations"</span>)</span>
<span id="cb22-262"><a href="#cb22-262" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-263"><a href="#cb22-263" aria-hidden="true" tabindex="-1"></a><span class="co"># Temperature-humidity statistics by layer</span></span>
<span id="cb22-264"><a href="#cb22-264" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">=== TEMPERATURE-HUMIDITY STATISTICS BY LAYER ==="</span>)</span>
<span id="cb22-265"><a href="#cb22-265" aria-hidden="true" tabindex="-1"></a>layer_stats <span class="op">=</span> analysis_data.groupby(<span class="st">'canopy_layer'</span>).agg({</span>
<span id="cb22-266"><a href="#cb22-266" aria-hidden="true" tabindex="-1"></a>    <span class="st">'humid_temp'</span>: [<span class="st">'mean'</span>, <span class="st">'std'</span>],</span>
<span id="cb22-267"><a href="#cb22-267" aria-hidden="true" tabindex="-1"></a>    <span class="st">'humidity'</span>: [<span class="st">'mean'</span>, <span class="st">'std'</span>]</span>
<span id="cb22-268"><a href="#cb22-268" aria-hidden="true" tabindex="-1"></a>}).<span class="bu">round</span>(<span class="dv">2</span>)</span>
<span id="cb22-269"><a href="#cb22-269" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(layer_stats)</span>
<span id="cb22-270"><a href="#cb22-270" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb22-271"><a href="#cb22-271" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-272"><a href="#cb22-272" aria-hidden="true" tabindex="-1"></a><span class="fu">## Finding 1: Temperature-Humidity Relationships Differ by Canopy Layer</span></span>
<span id="cb22-275"><a href="#cb22-275" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb22-276"><a href="#cb22-276" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: finding1-hexbin</span></span>
<span id="cb22-277"><a href="#cb22-277" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Temperature-humidity relationships across three canopy layers. Each panel shows hexbin density plots where darker red colors indicate higher density of observations. The upper canopy shows a clear inverse relationship between temperature and humidity, while the lower canopy shows a more diffuse pattern with points scattered throughout the parameter space."</span></span>
<span id="cb22-278"><a href="#cb22-278" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-279"><a href="#cb22-279" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> plot_temp_humidity_by_layer(data, figsize<span class="op">=</span>(<span class="dv">16</span>, <span class="dv">5</span>)):</span>
<span id="cb22-280"><a href="#cb22-280" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb22-281"><a href="#cb22-281" aria-hidden="true" tabindex="-1"></a><span class="co">    Plot temperature vs humidity relationship for different canopy layers</span></span>
<span id="cb22-282"><a href="#cb22-282" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb22-283"><a href="#cb22-283" aria-hidden="true" tabindex="-1"></a>    fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">3</span>, figsize<span class="op">=</span>figsize)</span>
<span id="cb22-284"><a href="#cb22-284" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb22-285"><a href="#cb22-285" aria-hidden="true" tabindex="-1"></a>    colors <span class="op">=</span> {<span class="st">'Lower'</span>: <span class="st">'forestgreen'</span>, <span class="st">'Middle'</span>: <span class="st">'orange'</span>, <span class="st">'Upper'</span>: <span class="st">'crimson'</span>}</span>
<span id="cb22-286"><a href="#cb22-286" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb22-287"><a href="#cb22-287" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> i, layer <span class="kw">in</span> <span class="bu">enumerate</span>([<span class="st">'Lower'</span>, <span class="st">'Middle'</span>, <span class="st">'Upper'</span>]):</span>
<span id="cb22-288"><a href="#cb22-288" aria-hidden="true" tabindex="-1"></a>        subset <span class="op">=</span> data[data[<span class="st">'canopy_layer'</span>] <span class="op">==</span> layer]</span>
<span id="cb22-289"><a href="#cb22-289" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb22-290"><a href="#cb22-290" aria-hidden="true" tabindex="-1"></a>        axes[i].hexbin(subset[<span class="st">'humid_temp'</span>], subset[<span class="st">'humidity'</span>], </span>
<span id="cb22-291"><a href="#cb22-291" aria-hidden="true" tabindex="-1"></a>                       gridsize<span class="op">=</span><span class="dv">30</span>, cmap<span class="op">=</span><span class="st">'YlOrRd'</span>, mincnt<span class="op">=</span><span class="dv">1</span>, alpha<span class="op">=</span><span class="fl">0.8</span>)</span>
<span id="cb22-292"><a href="#cb22-292" aria-hidden="true" tabindex="-1"></a>        axes[i].set_xlabel(<span class="st">'Temperature (°C)'</span>, fontsize<span class="op">=</span><span class="dv">12</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb22-293"><a href="#cb22-293" aria-hidden="true" tabindex="-1"></a>        axes[i].set_ylabel(<span class="st">'Relative Humidity (%)'</span>, fontsize<span class="op">=</span><span class="dv">12</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb22-294"><a href="#cb22-294" aria-hidden="true" tabindex="-1"></a>        axes[i].set_title(<span class="ss">f'</span><span class="sc">{</span>layer<span class="sc">}</span><span class="ss"> Canopy'</span>, fontsize<span class="op">=</span><span class="dv">14</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>, </span>
<span id="cb22-295"><a href="#cb22-295" aria-hidden="true" tabindex="-1"></a>                         color<span class="op">=</span>colors[layer])</span>
<span id="cb22-296"><a href="#cb22-296" aria-hidden="true" tabindex="-1"></a>        axes[i].grid(<span class="va">True</span>, alpha<span class="op">=</span><span class="fl">0.3</span>)</span>
<span id="cb22-297"><a href="#cb22-297" aria-hidden="true" tabindex="-1"></a>        n <span class="op">=</span> <span class="bu">len</span>(subset)</span>
<span id="cb22-298"><a href="#cb22-298" aria-hidden="true" tabindex="-1"></a>        axes[i].text(<span class="fl">0.05</span>, <span class="fl">0.95</span>, <span class="ss">f'n = </span><span class="sc">{</span>n<span class="sc">:,}</span><span class="ss">'</span>, transform<span class="op">=</span>axes[i].transAxes,</span>
<span id="cb22-299"><a href="#cb22-299" aria-hidden="true" tabindex="-1"></a>                    fontsize<span class="op">=</span><span class="dv">10</span>, verticalalignment<span class="op">=</span><span class="st">'top'</span>,</span>
<span id="cb22-300"><a href="#cb22-300" aria-hidden="true" tabindex="-1"></a>                    bbox<span class="op">=</span><span class="bu">dict</span>(boxstyle<span class="op">=</span><span class="st">'round'</span>, facecolor<span class="op">=</span><span class="st">'wheat'</span>, alpha<span class="op">=</span><span class="fl">0.5</span>))</span>
<span id="cb22-301"><a href="#cb22-301" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb22-302"><a href="#cb22-302" aria-hidden="true" tabindex="-1"></a>    plt.tight_layout()</span>
<span id="cb22-303"><a href="#cb22-303" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> fig</span>
<span id="cb22-304"><a href="#cb22-304" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-305"><a href="#cb22-305" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> plot_temp_humidity_by_layer(analysis_data)</span>
<span id="cb22-306"><a href="#cb22-306" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb22-307"><a href="#cb22-307" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb22-308"><a href="#cb22-308" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-309"><a href="#cb22-309" aria-hidden="true" tabindex="-1"></a>Across all layers, there is a clear negative relationship: as temperature increases, relative humidity decreases. The densest regions (darkest hexes) occur at high humidity and lower temperatures, especially in the Lower Canopy, indicating more frequent cool, moist conditions near the ground. Upper canopy measurements are generally warmer and slightly drier, highlighting consistent vertical microclimatic gradients in temperature and humidity through the forest canopy.</span>
<span id="cb22-310"><a href="#cb22-310" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-311"><a href="#cb22-311" aria-hidden="true" tabindex="-1"></a><span class="fu">## Finding 2: Temperature Distributions Are Similar Across Canopy Layers</span></span>
<span id="cb22-314"><a href="#cb22-314" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb22-315"><a href="#cb22-315" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: finding2-boxplots</span></span>
<span id="cb22-316"><a href="#cb22-316" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> plot_temperature_by_layer(data, figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">6</span>)):</span>
<span id="cb22-317"><a href="#cb22-317" aria-hidden="true" tabindex="-1"></a>    <span class="co">""" Box plot showing temperature distribution across canopy layers</span></span>
<span id="cb22-318"><a href="#cb22-318" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb22-319"><a href="#cb22-319" aria-hidden="true" tabindex="-1"></a>    fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>figsize)</span>
<span id="cb22-320"><a href="#cb22-320" aria-hidden="true" tabindex="-1"></a>    layers <span class="op">=</span> [<span class="st">'Lower'</span>, <span class="st">'Middle'</span>, <span class="st">'Upper'</span>]</span>
<span id="cb22-321"><a href="#cb22-321" aria-hidden="true" tabindex="-1"></a>    data_to_plot <span class="op">=</span> [data[data[<span class="st">'canopy_layer'</span>] <span class="op">==</span> layer][<span class="st">'humid_temp'</span>].dropna() </span>
<span id="cb22-322"><a href="#cb22-322" aria-hidden="true" tabindex="-1"></a>                    <span class="cf">for</span> layer <span class="kw">in</span> layers]</span>
<span id="cb22-323"><a href="#cb22-323" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb22-324"><a href="#cb22-324" aria-hidden="true" tabindex="-1"></a>    bp <span class="op">=</span> ax.boxplot(data_to_plot, labels<span class="op">=</span>layers, patch_artist<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb22-325"><a href="#cb22-325" aria-hidden="true" tabindex="-1"></a>                    boxprops<span class="op">=</span><span class="bu">dict</span>(facecolor<span class="op">=</span><span class="st">'lightcoral'</span>, alpha<span class="op">=</span><span class="fl">0.7</span>),</span>
<span id="cb22-326"><a href="#cb22-326" aria-hidden="true" tabindex="-1"></a>                    medianprops<span class="op">=</span><span class="bu">dict</span>(color<span class="op">=</span><span class="st">'darkred'</span>, linewidth<span class="op">=</span><span class="dv">2</span>),</span>
<span id="cb22-327"><a href="#cb22-327" aria-hidden="true" tabindex="-1"></a>                    showmeans<span class="op">=</span><span class="va">True</span>, </span>
<span id="cb22-328"><a href="#cb22-328" aria-hidden="true" tabindex="-1"></a>                    meanprops<span class="op">=</span><span class="bu">dict</span>(marker<span class="op">=</span><span class="st">'D'</span>, markerfacecolor<span class="op">=</span><span class="st">'blue'</span>, </span>
<span id="cb22-329"><a href="#cb22-329" aria-hidden="true" tabindex="-1"></a>                                  markeredgecolor<span class="op">=</span><span class="st">'blue'</span>, markersize<span class="op">=</span><span class="dv">8</span>))</span>
<span id="cb22-330"><a href="#cb22-330" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb22-331"><a href="#cb22-331" aria-hidden="true" tabindex="-1"></a>    ax.set_xlabel(<span class="st">'Canopy Layer'</span>, fontsize<span class="op">=</span><span class="dv">13</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb22-332"><a href="#cb22-332" aria-hidden="true" tabindex="-1"></a>    ax.set_ylabel(<span class="st">'Temperature (°C)'</span>, fontsize<span class="op">=</span><span class="dv">13</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb22-333"><a href="#cb22-333" aria-hidden="true" tabindex="-1"></a>    ax.set_title(<span class="st">'Temperature Distribution by Canopy Layer'</span>, </span>
<span id="cb22-334"><a href="#cb22-334" aria-hidden="true" tabindex="-1"></a>                 fontsize<span class="op">=</span><span class="dv">15</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb22-335"><a href="#cb22-335" aria-hidden="true" tabindex="-1"></a>    ax.grid(<span class="va">True</span>, alpha<span class="op">=</span><span class="fl">0.3</span>, axis<span class="op">=</span><span class="st">'y'</span>)</span>
<span id="cb22-336"><a href="#cb22-336" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> i, layer <span class="kw">in</span> <span class="bu">enumerate</span>(layers):</span>
<span id="cb22-337"><a href="#cb22-337" aria-hidden="true" tabindex="-1"></a>        n <span class="op">=</span> <span class="bu">len</span>(data_to_plot[i])</span>
<span id="cb22-338"><a href="#cb22-338" aria-hidden="true" tabindex="-1"></a>        ax.text(i<span class="op">+</span><span class="dv">1</span>, ax.get_ylim()[<span class="dv">0</span>] <span class="op">+</span> <span class="fl">0.5</span>, <span class="ss">f'n=</span><span class="sc">{</span>n<span class="sc">:,}</span><span class="ss">'</span>, </span>
<span id="cb22-339"><a href="#cb22-339" aria-hidden="true" tabindex="-1"></a>               ha<span class="op">=</span><span class="st">'center'</span>, va<span class="op">=</span><span class="st">'bottom'</span>, fontsize<span class="op">=</span><span class="dv">9</span>)</span>
<span id="cb22-340"><a href="#cb22-340" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb22-341"><a href="#cb22-341" aria-hidden="true" tabindex="-1"></a>    plt.tight_layout()</span>
<span id="cb22-342"><a href="#cb22-342" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> fig</span>
<span id="cb22-343"><a href="#cb22-343" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-344"><a href="#cb22-344" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> plot_temperature_by_layer(analysis_data)</span>
<span id="cb22-345"><a href="#cb22-345" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb22-346"><a href="#cb22-346" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb22-347"><a href="#cb22-347" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-348"><a href="#cb22-348" aria-hidden="true" tabindex="-1"></a>The box plots reveal a surprising result: despite being separated by up to 55 meters vertically and experiencing vastly different light environments, all three canopy layers show similar temperature distributions. The median temperatures (red lines) are approximately 15°C for all three layers, and the interquartile ranges (boxes) overlap substantially.</span>
<span id="cb22-349"><a href="#cb22-349" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-350"><a href="#cb22-350" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-351"><a href="#cb22-351" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-352"><a href="#cb22-352" aria-hidden="true" tabindex="-1"></a><span class="fu">## Finding 3: Height Influences Temperature-Humidity Coupling Strength</span></span>
<span id="cb22-355"><a href="#cb22-355" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb22-356"><a href="#cb22-356" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> plot_temp_vs_humidity_by_height(data, figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">8</span>)):</span>
<span id="cb22-357"><a href="#cb22-357" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb22-358"><a href="#cb22-358" aria-hidden="true" tabindex="-1"></a><span class="co">    Scatter plot of temperature vs humidity colored by height</span></span>
<span id="cb22-359"><a href="#cb22-359" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb22-360"><a href="#cb22-360" aria-hidden="true" tabindex="-1"></a>    fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>figsize)</span>
<span id="cb22-361"><a href="#cb22-361" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb22-362"><a href="#cb22-362" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb22-363"><a href="#cb22-363" aria-hidden="true" tabindex="-1"></a>    <span class="co">#sample = data.sample(n=min(5000, len(data)), random_state=42)</span></span>
<span id="cb22-364"><a href="#cb22-364" aria-hidden="true" tabindex="-1"></a>    sample<span class="op">=</span> data</span>
<span id="cb22-365"><a href="#cb22-365" aria-hidden="true" tabindex="-1"></a>    scatter <span class="op">=</span> ax.scatter(sample[<span class="st">'humid_temp'</span>], sample[<span class="st">'humidity'</span>], </span>
<span id="cb22-366"><a href="#cb22-366" aria-hidden="true" tabindex="-1"></a>                        c<span class="op">=</span>sample[<span class="st">'Height'</span>], cmap<span class="op">=</span><span class="st">'viridis'</span>, </span>
<span id="cb22-367"><a href="#cb22-367" aria-hidden="true" tabindex="-1"></a>                        alpha<span class="op">=</span><span class="fl">0.6</span>, s<span class="op">=</span><span class="dv">20</span>, edgecolors<span class="op">=</span><span class="st">'none'</span>)</span>
<span id="cb22-368"><a href="#cb22-368" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb22-369"><a href="#cb22-369" aria-hidden="true" tabindex="-1"></a>    ax.set_xlabel(<span class="st">'Temperature (°C)'</span>, fontsize<span class="op">=</span><span class="dv">13</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb22-370"><a href="#cb22-370" aria-hidden="true" tabindex="-1"></a>    ax.set_ylabel(<span class="st">'Relative Humidity (%)'</span>, fontsize<span class="op">=</span><span class="dv">13</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb22-371"><a href="#cb22-371" aria-hidden="true" tabindex="-1"></a>    ax.set_title(<span class="st">'Temperature-Humidity Relationship by Canopy Height'</span>, </span>
<span id="cb22-372"><a href="#cb22-372" aria-hidden="true" tabindex="-1"></a>                 fontsize<span class="op">=</span><span class="dv">15</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb22-373"><a href="#cb22-373" aria-hidden="true" tabindex="-1"></a>    ax.grid(<span class="va">True</span>, alpha<span class="op">=</span><span class="fl">0.3</span>)</span>
<span id="cb22-374"><a href="#cb22-374" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb22-375"><a href="#cb22-375" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Colorbar</span></span>
<span id="cb22-376"><a href="#cb22-376" aria-hidden="true" tabindex="-1"></a>    cbar <span class="op">=</span> plt.colorbar(scatter, ax<span class="op">=</span>ax)</span>
<span id="cb22-377"><a href="#cb22-377" aria-hidden="true" tabindex="-1"></a>    cbar.set_label(<span class="st">'Height Above Ground (m)'</span>, fontsize<span class="op">=</span><span class="dv">12</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb22-378"><a href="#cb22-378" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb22-379"><a href="#cb22-379" aria-hidden="true" tabindex="-1"></a>    plt.tight_layout()</span>
<span id="cb22-380"><a href="#cb22-380" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> fig</span>
<span id="cb22-381"><a href="#cb22-381" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-382"><a href="#cb22-382" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> plot_temp_vs_humidity_by_height(analysis_data)</span>
<span id="cb22-383"><a href="#cb22-383" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb22-384"><a href="#cb22-384" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb22-385"><a href="#cb22-385" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-386"><a href="#cb22-386" aria-hidden="true" tabindex="-1"></a>Relative humidity decreases when temperature increases, showing a clear inverse relationship between these two variables. Point color indicates height above ground, revealing that measurements from higher canopy layers tend to be slightly warmer and drier, while lower layers are cooler and more humid. This pattern highlights a vertical microclimatic gradient within the forest canopy, with lower layers experiencing more moisture and variability, and upper layers being drier and thermally more stable.</span>
<span id="cb22-387"><a href="#cb22-387" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-388"><a href="#cb22-388" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-389"><a href="#cb22-389" aria-hidden="true" tabindex="-1"></a><span class="fu">## Finding 4: Humidity Relationship with Height</span></span>
<span id="cb22-392"><a href="#cb22-392" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb22-393"><a href="#cb22-393" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: finding4-humidity-height</span></span>
<span id="cb22-394"><a href="#cb22-394" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Relationship between canopy height and relative humidity. Each point represents a single measurement, colored by temperature. The clear downward trend shows that humidity systematically decreases with increasing height above ground."</span></span>
<span id="cb22-395"><a href="#cb22-395" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-396"><a href="#cb22-396" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> plot_humidity_vs_height(data, figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">7</span>)):</span>
<span id="cb22-397"><a href="#cb22-397" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb22-398"><a href="#cb22-398" aria-hidden="true" tabindex="-1"></a><span class="co">    Simple scatter plot of humidity vs height</span></span>
<span id="cb22-399"><a href="#cb22-399" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb22-400"><a href="#cb22-400" aria-hidden="true" tabindex="-1"></a>    fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>figsize)</span>
<span id="cb22-401"><a href="#cb22-401" aria-hidden="true" tabindex="-1"></a>    sample <span class="op">=</span> data.sample(n<span class="op">=</span><span class="bu">min</span>(<span class="dv">3000</span>, <span class="bu">len</span>(data)), random_state<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb22-402"><a href="#cb22-402" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb22-403"><a href="#cb22-403" aria-hidden="true" tabindex="-1"></a>    scatter <span class="op">=</span> ax.scatter(sample[<span class="st">'humidity'</span>], sample[<span class="st">'Height'</span>], </span>
<span id="cb22-404"><a href="#cb22-404" aria-hidden="true" tabindex="-1"></a>                        c<span class="op">=</span>sample[<span class="st">'humid_temp'</span>], cmap<span class="op">=</span><span class="st">'coolwarm'</span>, </span>
<span id="cb22-405"><a href="#cb22-405" aria-hidden="true" tabindex="-1"></a>                        alpha<span class="op">=</span><span class="fl">0.5</span>, s<span class="op">=</span><span class="dv">15</span>, edgecolors<span class="op">=</span><span class="st">'none'</span>)</span>
<span id="cb22-406"><a href="#cb22-406" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb22-407"><a href="#cb22-407" aria-hidden="true" tabindex="-1"></a>    ax.set_xlabel(<span class="st">'Relative Humidity (%)'</span>, fontsize<span class="op">=</span><span class="dv">13</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb22-408"><a href="#cb22-408" aria-hidden="true" tabindex="-1"></a>    ax.set_ylabel(<span class="st">'Height Above Ground (m)'</span>, fontsize<span class="op">=</span><span class="dv">13</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb22-409"><a href="#cb22-409" aria-hidden="true" tabindex="-1"></a>    ax.set_title(<span class="st">'Humidity Decreases with Canopy Height'</span>, </span>
<span id="cb22-410"><a href="#cb22-410" aria-hidden="true" tabindex="-1"></a>                 fontsize<span class="op">=</span><span class="dv">15</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb22-411"><a href="#cb22-411" aria-hidden="true" tabindex="-1"></a>    ax.grid(<span class="va">True</span>, alpha<span class="op">=</span><span class="fl">0.3</span>)</span>
<span id="cb22-412"><a href="#cb22-412" aria-hidden="true" tabindex="-1"></a>    cbar <span class="op">=</span> plt.colorbar(scatter, ax<span class="op">=</span>ax)</span>
<span id="cb22-413"><a href="#cb22-413" aria-hidden="true" tabindex="-1"></a>    cbar.set_label(<span class="st">'Temperature (°C)'</span>, fontsize<span class="op">=</span><span class="dv">12</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb22-414"><a href="#cb22-414" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb22-415"><a href="#cb22-415" aria-hidden="true" tabindex="-1"></a>    plt.tight_layout()</span>
<span id="cb22-416"><a href="#cb22-416" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> fig</span>
<span id="cb22-417"><a href="#cb22-417" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-418"><a href="#cb22-418" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> plot_humidity_vs_height(analysis_data)</span>
<span id="cb22-419"><a href="#cb22-419" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb22-420"><a href="#cb22-420" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb22-421"><a href="#cb22-421" aria-hidden="true" tabindex="-1"></a>As canopy height increases, relative humidity tends to decrease and temperature tends to cool, reflecting microclimatic changes through the forest vertical structure. Lower layers are warmer and more variable in moisture, while upper layers are cooler and slightly drier.</span>
<span id="cb22-422"><a href="#cb22-422" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-423"><a href="#cb22-423" aria-hidden="true" tabindex="-1"></a><span class="fu">## Finding 5: Humidity Distributions by Canopy Layer</span></span>
<span id="cb22-424"><a href="#cb22-424" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-425"><a href="#cb22-425" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-426"><a href="#cb22-426" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-429"><a href="#cb22-429" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb22-430"><a href="#cb22-430" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> plot_humidity_violins(data, figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">6</span>)):</span>
<span id="cb22-431"><a href="#cb22-431" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb22-432"><a href="#cb22-432" aria-hidden="true" tabindex="-1"></a><span class="co">    Violin plot of humidity by canancy layer</span></span>
<span id="cb22-433"><a href="#cb22-433" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb22-434"><a href="#cb22-434" aria-hidden="true" tabindex="-1"></a>    <span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt  <span class="co"># Move import to TOP</span></span>
<span id="cb22-435"><a href="#cb22-435" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb22-436"><a href="#cb22-436" aria-hidden="true" tabindex="-1"></a>    fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>figsize)</span>
<span id="cb22-437"><a href="#cb22-437" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb22-438"><a href="#cb22-438" aria-hidden="true" tabindex="-1"></a>    layers <span class="op">=</span> [<span class="st">'Lower'</span>, <span class="st">'Middle'</span>, <span class="st">'Upper'</span>]</span>
<span id="cb22-439"><a href="#cb22-439" aria-hidden="true" tabindex="-1"></a>    data_to_plot <span class="op">=</span> [data[data[<span class="st">'canopy_layer'</span>] <span class="op">==</span> layer][<span class="st">'humidity'</span>].dropna().values </span>
<span id="cb22-440"><a href="#cb22-440" aria-hidden="true" tabindex="-1"></a>                    <span class="cf">for</span> layer <span class="kw">in</span> layers]</span>
<span id="cb22-441"><a href="#cb22-441" aria-hidden="true" tabindex="-1"></a>    colors <span class="op">=</span> [<span class="st">'forestgreen'</span>, <span class="st">'orange'</span>, <span class="st">'pink'</span>]</span>
<span id="cb22-442"><a href="#cb22-442" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb22-443"><a href="#cb22-443" aria-hidden="true" tabindex="-1"></a>    parts <span class="op">=</span> ax.violinplot(data_to_plot, positions<span class="op">=</span>[<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>], </span>
<span id="cb22-444"><a href="#cb22-444" aria-hidden="true" tabindex="-1"></a>                          showmeans<span class="op">=</span><span class="va">True</span>, showmedians<span class="op">=</span><span class="va">True</span>, widths<span class="op">=</span><span class="fl">0.7</span>)</span>
<span id="cb22-445"><a href="#cb22-445" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb22-446"><a href="#cb22-446" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> i, pc <span class="kw">in</span> <span class="bu">enumerate</span>(parts[<span class="st">'bodies'</span>]):</span>
<span id="cb22-447"><a href="#cb22-447" aria-hidden="true" tabindex="-1"></a>        pc.set_facecolor(colors[i])</span>
<span id="cb22-448"><a href="#cb22-448" aria-hidden="true" tabindex="-1"></a>        pc.set_alpha(<span class="fl">0.5</span>)</span>
<span id="cb22-449"><a href="#cb22-449" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb22-450"><a href="#cb22-450" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Color the lines</span></span>
<span id="cb22-451"><a href="#cb22-451" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> partname <span class="kw">in</span> (<span class="st">'cbars'</span>, <span class="st">'cmins'</span>, <span class="st">'cmaxes'</span>, <span class="st">'cmedians'</span>, <span class="st">'cmeans'</span>):</span>
<span id="cb22-452"><a href="#cb22-452" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> partname <span class="kw">in</span> parts:</span>
<span id="cb22-453"><a href="#cb22-453" aria-hidden="true" tabindex="-1"></a>            parts[partname].set_edgecolor(<span class="st">'black'</span>)</span>
<span id="cb22-454"><a href="#cb22-454" aria-hidden="true" tabindex="-1"></a>            parts[partname].set_linewidth(<span class="fl">1.5</span>)</span>
<span id="cb22-455"><a href="#cb22-455" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb22-456"><a href="#cb22-456" aria-hidden="true" tabindex="-1"></a>    ax.set_xticks([<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>])</span>
<span id="cb22-457"><a href="#cb22-457" aria-hidden="true" tabindex="-1"></a>    ax.set_xticklabels(layers)</span>
<span id="cb22-458"><a href="#cb22-458" aria-hidden="true" tabindex="-1"></a>    ax.set_xlabel(<span class="st">'Canopy Layer'</span>, fontsize<span class="op">=</span><span class="dv">13</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb22-459"><a href="#cb22-459" aria-hidden="true" tabindex="-1"></a>    ax.set_ylabel(<span class="st">'Relative Humidity (%)'</span>, fontsize<span class="op">=</span><span class="dv">13</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb22-460"><a href="#cb22-460" aria-hidden="true" tabindex="-1"></a>    ax.set_title(<span class="st">'Humidity Distribution by Canopy Layer'</span>, </span>
<span id="cb22-461"><a href="#cb22-461" aria-hidden="true" tabindex="-1"></a>                 fontsize<span class="op">=</span><span class="dv">15</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb22-462"><a href="#cb22-462" aria-hidden="true" tabindex="-1"></a>    ax.grid(<span class="va">True</span>, alpha<span class="op">=</span><span class="fl">0.3</span>, axis<span class="op">=</span><span class="st">'y'</span>)</span>
<span id="cb22-463"><a href="#cb22-463" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb22-464"><a href="#cb22-464" aria-hidden="true" tabindex="-1"></a>    plt.tight_layout()</span>
<span id="cb22-465"><a href="#cb22-465" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> fig</span>
<span id="cb22-466"><a href="#cb22-466" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-467"><a href="#cb22-467" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> plot_humidity_violins(analysis_data)</span>
<span id="cb22-468"><a href="#cb22-468" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb22-469"><a href="#cb22-469" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb22-470"><a href="#cb22-470" aria-hidden="true" tabindex="-1"></a>Median humidity values are similar across layers, approximately 55–60%, indicating that typical humidity is consistent throughout the canopy. However, the distribution shapes reveal layer-specific variability. The Lower and Middle layers exhibit wider spreads at low humidity values, suggesting that these layers experience more frequent dry conditions. In contrast, the Upper layer shows a slightly narrower distribution around the median, with fewer extremely low values, though it still reaches high humidity levels. Overall, while central tendencies are similar, the lower and middle canopy layers are subject to greater fluctuations in relative humidity, likely reflecting microclimatic effects such as differential sunlight exposure and airflow.</span>
<span id="cb22-471"><a href="#cb22-471" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-472"><a href="#cb22-472" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-473"><a href="#cb22-473" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-474"><a href="#cb22-474" aria-hidden="true" tabindex="-1"></a><span class="fu"># Discussion</span></span>
<span id="cb22-475"><a href="#cb22-475" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-476"><a href="#cb22-476" aria-hidden="true" tabindex="-1"></a>This analysis demonstrates that temperature-humidity relationships in redwood canopies vary systematically with vertical position, revealing fundamentally different environmental processes operating at different heights. The three key findings tell a coherent story about canopy microclimate structure:</span>
<span id="cb22-477"><a href="#cb22-477" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-478"><a href="#cb22-478" aria-hidden="true" tabindex="-1"></a>The strength of temperature-humidity coupling increases with height. Upper canopy sensors show tight inverse relationships characteristic of direct atmospheric forcing, while lower canopy sensors show weak, diffuse relationships indicating buffering and decoupling from atmospheric conditions. This gradient in coupling strength reflects the transition from exposed, atmosphere-dominated conditions at the top to buffered, tree-physiology-influenced conditions at the bottom.</span>
<span id="cb22-479"><a href="#cb22-479" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-480"><a href="#cb22-480" aria-hidden="true" tabindex="-1"></a>Second, despite dramatic differences in light exposure and humidity levels, temperature remains relatively uniform across canopy heights. This thermal uniformity, combined with varying humidity, creates distinct microenvironments: the upper canopy is warm and dry while the lower canopy is warm and humid. The combination of similar temperatures but different humidities means that vapor pressure deficit (the driving force for transpiration) varies substantially with height even though temperature alone would suggest similar conditions.</span>
<span id="cb22-481"><a href="#cb22-481" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-482"><a href="#cb22-482" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-483"><a href="#cb22-483" aria-hidden="true" tabindex="-1"></a>From a tree physiology perspective, these findings have important implications. The upper canopy operates under high evaporative demand (low humidity) despite moderate temperatures, requiring substantial water transport from roots. The tight temperature-humidity coupling means that upper leaves experience coordinated stress from both factors. The lower canopy benefits from high humidity reducing water stress, and the weak temperature-humidity coupling means that fog events can raise humidity independent of temperature changes, providing additional moisture without requiring temperature drops.</span>
<span id="cb22-484"><a href="#cb22-484" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-485"><a href="#cb22-485" aria-hidden="true" tabindex="-1"></a>These patterns also highlight the limitations of using temperature alone as a microclimate indicator. Two positions with identical temperatures (as seen in Finding 2) can have dramatically different humidity levels and different environmental forcing mechanisms (as seen in Findings 1 and 3). A complete understanding of canopy microclimate requires examining multiple variables and their relationships, not just their individual distributions.</span>
<span id="cb22-486"><a href="#cb22-486" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-487"><a href="#cb22-487" aria-hidden="true" tabindex="-1"></a>Future work could examine how these temperature-humidity relationships vary diurnally (day versus night), seasonally, or during specific weather events like fog intrusions or heat waves. Comparing multiple trees or forest stands would test whether these patterns are general features of tall forest canopies or specific to this particular redwood tree and its coastal location.</span>
</code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->




</body></html>